In [3]:
!pip install pandas pyarrow

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (14.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [1]:
# IMPORTS
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

#Fin Data Sources
import yfinance as yf
import pandas_datareader as pdr

#Data viz
import plotly.graph_objs as go
import plotly.express as px

import time
from datetime import date

# for graphs
import matplotlib.pyplot as plt

**Question 1: IPO Filings Web Scraping and Data Processing**

What's the total sum ($m) of 2023 filings that happened on Fridays?

In [ ]:
import pandas as pd
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3',
}

url = "https://stockanalysis.com/ipos/filings/"
response = requests.get(url, headers=headers)

ipo_dfs = pd.read_html(response.text)

In [ ]:
ipos_filings = ipo_dfs[0]
ipos_filings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Filing Date     325 non-null    object
 1   Symbol          325 non-null    object
 2   Company Name    325 non-null    object
 3   Price Range     325 non-null    object
 4   Shares Offered  325 non-null    object
dtypes: object(5)
memory usage: 12.8+ KB

In [ ]:
ipos_filings

,Filing Date,Symbol,Company Name,Price Range,Shares Offered
0,"May 3, 2024",TBN,Tamboran Resources Corporation,-,-
1,"Apr 29, 2024",HWEC,"HW Electro Co., Ltd.",$3.00,3750000
2,"Apr 29, 2024",DTSQ,DT Cloud Star Acquisition Corporation,$10.00,6000000
3,"Apr 26, 2024",EURK,Eureka Acquisition Corp,$10.00,5000000
4,"Apr 26, 2024",HDL,Super Hi International Holding Ltd.,-,-
...,...,...,...,...,...
320,"Jan 21, 2020",GOXS,"Goxus, Inc.",$8.00 - $10.00,1500000
321,"Jan 21, 2020",UTXO,"UTXO Acquisition, Inc.",$10.00,5000000
322,"Dec 9, 2019",LOHA,Loha Co. Ltd,$8.00 - $10.00,2500000
323,"Oct 4, 2019",ZGHB,China Eco-Materials Group Co. Limited,$4.00,4300000
324,"Dec 27, 2018",FBOX,Fit Boxx Holdings Limited,$5.00 - $6.50,2000000

In [ ]:
# convert to datetime
ipos_filings['Filing Date'] = pd.to_datetime(ipos_filings['Filing Date'],format='mixed')
ipos_filings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Filing Date     325 non-null    datetime64[ns]
 1   Symbol          325 non-null    object
 2   Company Name    325 non-null    object
 3   Price Range     325 non-null    object
 4   Shares Offered  325 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 12.8+ KB

In [ ]:
ipos_filings

,Filing Date,Symbol,Company Name,Price Range,Shares Offered
0,2024-05-03,TBN,Tamboran Resources Corporation,-,-
1,2024-04-29,HWEC,"HW Electro Co., Ltd.",$3.00,3750000
2,2024-04-29,DTSQ,DT Cloud Star Acquisition Corporation,$10.00,6000000
3,2024-04-26,EURK,Eureka Acquisition Corp,$10.00,5000000
4,2024-04-26,HDL,Super Hi International Holding Ltd.,-,-
...,...,...,...,...,...
320,2020-01-21,GOXS,"Goxus, Inc.",$8.00 - $10.00,1500000
321,2020-01-21,UTXO,"UTXO Acquisition, Inc.",$10.00,5000000
322,2019-12-09,LOHA,Loha Co. Ltd,$8.00 - $10.00,2500000
323,2019-10-04,ZGHB,China Eco-Materials Group Co. Limited,$4.00,4300000
324,2018-12-27,FBOX,Fit Boxx Holdings Limited,$5.00 - $6.50,2000000

In [ ]:
# Filter data for 2023
ipos_filings_2023 = ipos_filings[(ipos_filings['Filing Date'] > '2022-12-31') & (ipos_filings['Filing Date'] < '2024-01-01')]
ipos_filings_2023 = ipos_filings_2023.reset_index(drop=True)
ipos_filings_2023

,Filing Date,Symbol,Company Name,Price Range,Shares Offered
0,2023-12-29,LEC,Lafayette Energy Corp,$3.50 - $4.50,1200000
1,2023-12-29,EPSM,Epsium Enterprise Limited,-,-
2,2023-12-28,ONDR,"Sushi Ginza Onodera, Inc.",$7.00 - $8.00,1066667
3,2023-12-27,JDZG,Jiade Limited,$4.00 - $5.00,2200000
4,2023-12-22,LZMH,LZ Technology Holdings Limited,-,-
...,...,...,...,...,...
112,2023-01-31,FBGL,FBS Global Limited,$4.00 - $5.00,1875000
113,2023-01-24,THNK,"T1V, Inc.",$4.00 - $6.00,3300000
114,2023-01-23,RPET,New Ruipeng Pet Group Inc.,-,-
115,2023-01-13,RVGO,"RVeloCITY, Inc.",$4.00 - $5.00,3750000
116,2023-01-10,FDAN,FD Technology Inc.,$4.00 - $6.00,3500000

In [ ]:
missing_prices_df = ipos_filings_2023[ipos_filings_2023['Price Range'].astype(str).str.find('-') >= 0]
missing_prices_df

,Filing Date,Symbol,Company Name,Price Range,Shares Offered
0,2023-12-29,LEC,Lafayette Energy Corp,$3.50 - $4.50,1200000
1,2023-12-29,EPSM,Epsium Enterprise Limited,-,-
2,2023-12-28,ONDR,"Sushi Ginza Onodera, Inc.",$7.00 - $8.00,1066667
3,2023-12-27,JDZG,Jiade Limited,$4.00 - $5.00,2200000
4,2023-12-22,LZMH,LZ Technology Holdings Limited,-,-
...,...,...,...,...,...
112,2023-01-31,FBGL,FBS Global Limited,$4.00 - $5.00,1875000
113,2023-01-24,THNK,"T1V, Inc.",$4.00 - $6.00,3300000
114,2023-01-23,RPET,New Ruipeng Pet Group Inc.,-,-
115,2023-01-13,RVGO,"RVeloCITY, Inc.",$4.00 - $5.00,3750000
116,2023-01-10,FDAN,FD Technology Inc.,$4.00 - $6.00,3500000

In [ ]:
# Convert "Shares Offered" column
ipos_filings_2023['Shares Offered'] = pd.to_numeric(ipos_filings_2023['Shares Offered'].str.replace('$', ''), errors='coerce')
ipos_filings_2023['Shares Offered'] = pd.to_numeric(ipos_filings_2023['Shares Offered'])

In [ ]:
ipos_filings_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Filing Date     117 non-null    datetime64[ns]
 1   Symbol          117 non-null    object
 2   Company Name    117 non-null    object
 3   Price Range     117 non-null    object
 4   Shares Offered  86 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 4.7+ KB

In [ ]:
ipos_filings_2023.isnull().sum()

Filing Date        0
Symbol             0
Company Name       0
Price Range        0
Shares Offered    31
dtype: int64

In [ ]:
ipos_filings_2023

,Filing Date,Symbol,Company Name,Price Range,Shares Offered
0,2023-12-29,LEC,Lafayette Energy Corp,$3.50 - $4.50,1200000.0
1,2023-12-29,EPSM,Epsium Enterprise Limited,-,NaN
2,2023-12-28,ONDR,"Sushi Ginza Onodera, Inc.",$7.00 - $8.00,1066667.0
3,2023-12-27,JDZG,Jiade Limited,$4.00 - $5.00,2200000.0
4,2023-12-22,LZMH,LZ Technology Holdings Limited,-,NaN
...,...,...,...,...,...
112,2023-01-31,FBGL,FBS Global Limited,$4.00 - $5.00,1875000.0
113,2023-01-24,THNK,"T1V, Inc.",$4.00 - $6.00,3300000.0
114,2023-01-23,RPET,New Ruipeng Pet Group Inc.,-,NaN
115,2023-01-13,RVGO,"RVeloCITY, Inc.",$4.00 - $5.00,3750000.0
116,2023-01-10,FDAN,FD Technology Inc.,$4.00 - $6.00,3500000.0

In [ ]:
def parse_price_range(price_range):
    """
    Parses the price range string and returns the average price.
    """
    if pd.isna(price_range):
        return np.nan

    # Remove dollar signs and split the range
    prices = price_range.replace("$", "").split(" - ")

    if len(prices) == 1:
        # Only one price is available
        try:
            return float(prices[0])
        # No price is available
        except ValueError:
            return np.nan
    else:
        # Calculate average of two prices
        try:
            price1, price2 = float(prices[0]), float(prices[1])
            return (price1 + price2) / 2
        except ValueError:
            return np.nan

# Apply the function to create a new column 'Avg_price'
ipos_filings_2023["Avg_price"] = ipos_filings_2023["Price Range"].apply(parse_price_range)

print(ipos_filings_2023)

    Filing Date Symbol                    Company Name    Price Range  \
0    2023-12-29    LEC           Lafayette Energy Corp  $3.50 - $4.50
1    2023-12-29   EPSM       Epsium Enterprise Limited              -
2    2023-12-28   ONDR       Sushi Ginza Onodera, Inc.  $7.00 - $8.00
3    2023-12-27   JDZG                   Jiade Limited  $4.00 - $5.00
4    2023-12-22   LZMH  LZ Technology Holdings Limited              -
..          ...    ...                             ...            ...
112  2023-01-31   FBGL              FBS Global Limited  $4.00 - $5.00
113  2023-01-24   THNK                       T1V, Inc.  $4.00 - $6.00
114  2023-01-23   RPET      New Ruipeng Pet Group Inc.              -
115  2023-01-13   RVGO                 RVeloCITY, Inc.  $4.00 - $5.00
116  2023-01-10   FDAN              FD Technology Inc.  $4.00 - $6.00

     Shares Offered  Avg_price
0         1200000.0        4.0
1               NaN        NaN
2         1066667.0        7.5
3         2200000.0        4.5
4               NaN        NaN
..              ...        ...
112       1875000.0        4.5
113       3300000.0        5.0
114             NaN        NaN
115       3750000.0        4.5
116       3500000.0        5.0

[117 rows x 6 columns]

In [ ]:
# Create a new column "Shares_offered_value"
ipos_filings_2023['Shares_offered_value'] = ipos_filings_2023['Shares Offered'] * ipos_filings_2023['Avg_price']
print(ipos_filings_2023)

    Filing Date Symbol                    Company Name    Price Range  \
0    2023-12-29    LEC           Lafayette Energy Corp  $3.50 - $4.50
1    2023-12-29   EPSM       Epsium Enterprise Limited              -
2    2023-12-28   ONDR       Sushi Ginza Onodera, Inc.  $7.00 - $8.00
3    2023-12-27   JDZG                   Jiade Limited  $4.00 - $5.00
4    2023-12-22   LZMH  LZ Technology Holdings Limited              -
..          ...    ...                             ...            ...
112  2023-01-31   FBGL              FBS Global Limited  $4.00 - $5.00
113  2023-01-24   THNK                       T1V, Inc.  $4.00 - $6.00
114  2023-01-23   RPET      New Ruipeng Pet Group Inc.              -
115  2023-01-13   RVGO                 RVeloCITY, Inc.  $4.00 - $5.00
116  2023-01-10   FDAN              FD Technology Inc.  $4.00 - $6.00

     Shares Offered  Avg_price  Shares_offered_value
0         1200000.0        4.0             4800000.0
1               NaN        NaN                   NaN
2         1066667.0        7.5             8000002.5
3         2200000.0        4.5             9900000.0
4               NaN        NaN                   NaN
..              ...        ...                   ...
112       1875000.0        4.5             8437500.0
113       3300000.0        5.0            16500000.0
114             NaN        NaN                   NaN
115       3750000.0        4.5            16875000.0
116       3500000.0        5.0            17500000.0

[117 rows x 7 columns]

In [ ]:
# Filter data for Fridays (Date.dt.dayofweek()==4)
ipos_filings_2023_fridays = ipos_filings_2023[ipos_filings_2023["Filing Date"].dt.dayofweek == 4]
print(ipos_filings_2023_fridays)

    Filing Date Symbol                                     Company Name  \
0    2023-12-29    LEC                            Lafayette Energy Corp
1    2023-12-29   EPSM                        Epsium Enterprise Limited
4    2023-12-22   LZMH                   LZ Technology Holdings Limited
5    2023-12-22   CHLW  Chun Hui Le Wan International Holding Group Ltd
10   2023-12-15    GIT      Going International Holding Company Limited
12   2023-12-08   ENGS                            Energys Group Limited
13   2023-12-08   LNKS                       Linkers Industries Limited
32   2023-10-27    RAY                          Raytech Holding Limited
39   2023-10-13   ORIS                   Oriental Rise Holdings Limited
42   2023-10-06   QMMM                            QMMM Holdings Limited
46   2023-09-29   KAPA                              Kairos Pharma, Ltd.
47   2023-09-29   VAPA                        Valens Pay Global Limited
53   2023-09-15   ACSB                      Acesis Holdings Corporation
59   2023-08-11   ZXTY                      Zhongxing Holding Group Ltd
63   2023-08-04    JZL                     Jizhilong Holding Group Ltd.
71   2023-07-07    AZI         Autozi Internet Technology (Global) Ltd.
74   2023-06-30   SUBL                       BioLingus (Cayman) Limited
75   2023-06-30   RLND                        The RoyaLand Company Ltd.
76   2023-06-23    MSW                Ming Shing Group Holdings Limited
79   2023-06-09   MDRN                   Modern Mining Technology Corp.
84   2023-04-28   MJID                      Majestic Ideal Holdings Ltd
87   2023-04-21   XJET                                        XJet Ltd.
88   2023-04-21    JPO                              JP Outfitters, Inc.
89   2023-03-31   SUNH                          Xuhang Holdings Limited
90   2023-03-31   OSTX                        OS Therapies Incorporated
91   2023-03-31   GFCX                        GoodFaith Technology Inc.
93   2023-03-24   USEE                     USEE Electronic Commerce Ltd
99   2023-02-24    NTV                              NeoTV Group Limited
100  2023-02-24   BSME                    MED EIBY Holding Co., Limited
106  2023-02-10   WETO                      Webus International Limited
107  2023-02-10   HXHX                          Haoxin Holdings Limited
115  2023-01-13   RVGO                                  RVeloCITY, Inc.

       Price Range  Shares Offered  Avg_price  Shares_offered_value
0    $3.50 - $4.50       1200000.0       4.00             4800000.0
1                -             NaN        NaN                   NaN
4                -             NaN        NaN                   NaN
5                -             NaN        NaN                   NaN
10               -             NaN        NaN                   NaN
12   $4.00 - $6.00       2000000.0       5.00            10000000.0
13   $4.00 - $6.00       2200000.0       5.00            11000000.0
32   $4.00 - $5.00       1500000.0       4.50             6750000.0
39           $4.00       2000000.0       4.00             8000000.0
42           $4.00       2125000.0       4.00             8500000.0
46           $4.00       1550000.0       4.00             6200000.0
47   $5.00 - $6.00       1000000.0       5.50             5500000.0
53   $4.00 - $6.00       1300000.0       5.00             6500000.0
59               -             NaN        NaN                   NaN
63               -             NaN        NaN                   NaN
71   $4.00 - $5.00       1250000.0       4.50             5625000.0
74          $20.00        360000.0      20.00             7200000.0
75   $5.00 - $6.00       1250000.0       5.50             6875000.0
76   $5.00 - $8.00       1500000.0       6.50             9750000.0
79   $4.50 - $5.50       2000000.0       5.00            10000000.0
84   $4.00 - $5.00       2500000.0       4.50            11250000.0
87           $4.00       1600000.0       4.00             6400000.0
88           $4.00       2400000.0       4.00             9600000.0
89   $4.00 - $5.00       2750000.0       4.50            12375000.0
90           $5.00       2000000.0       5.00            10000000.0
91   $4.00 - $6.00       3000000.0       5.00            15000000.0
93               -             NaN        NaN                   NaN
99   $6.00 - $6.50       6800000.0       6.25            42500000.0
100  $4.00 - $6.00       4000000.0       5.00            20000000.0
106  $4.00 - $6.00       4000000.0       5.00            20000000.0
107  $4.00 - $6.00       3000000.0       5.00            15000000.0
115  $4.00 - $5.00       3750000.0       4.50            16875000.0

In [ ]:
ipos_filings_2023_fridays.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 0 to 115
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Filing Date           32 non-null     datetime64[ns]
 1   Symbol                32 non-null     object
 2   Company Name          32 non-null     object
 3   Price Range           32 non-null     object
 4   Shares Offered        25 non-null     float64
 5   Avg_price             25 non-null     float64
 6   Shares_offered_value  25 non-null     float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 2.0+ KB

In [ ]:
# Total sum in $m (millions of USD, closest INTEGER number) for all filings during 2023
print(ipos_filings_2023_fridays['Shares_offered_value'].sum())

285700000.0

So, it can be observed that the total sum ($m) of 2023 filings that happened on Fridays is around 286.

**Question 2: IPOs "Fixed days hold" strategy**

Find the optimal number of days X (between 1 and 30), where 75% quantile growth is the highest?

In [ ]:
url = "https://stockanalysis.com/ipos/2023/"
response = requests.get(url, headers=headers)

ipo_dfs = pd.read_html(response.text)

In [ ]:
ipos_2023 = ipo_dfs[0]
ipos_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   IPO Date      154 non-null    object
 1   Symbol        154 non-null    object
 2   Company Name  154 non-null    object
 3   IPO Price     154 non-null    object
 4   Current       154 non-null    object
 5   Return        154 non-null    object
dtypes: object(6)
memory usage: 7.3+ KB

In [ ]:
url = "https://stockanalysis.com/ipos/2024/"
response = requests.get(url, headers=headers)

ipo_dfs = pd.read_html(response.text)

In [ ]:
ipos_2024 = ipo_dfs[0]
ipos_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   IPO Date      64 non-null     object
 1   Symbol        64 non-null     object
 2   Company Name  64 non-null     object
 3   IPO Price     64 non-null     object
 4   Current       64 non-null     object
 5   Return        64 non-null     object
dtypes: object(6)
memory usage: 3.1+ KB

In [ ]:
stacked_ipos_df = pd.concat([ipos_2024, ipos_2023], ignore_index=True)
stacked_ipos_df

,IPO Date,Symbol,Company Name,IPO Price,Current,Return
0,"May 1, 2024",VIK,Viking Holdings Ltd.,$24.00,$28.65,20.98%
1,"Apr 26, 2024",ZONE,"CleanCore Solutions, Inc.",$4.00,$3.15,-22.50%
2,"Apr 25, 2024",RBRK,"Rubrik, Inc.",$32.00,$33.77,5.25%
3,"Apr 25, 2024",LOAR,Loar Holdings Inc.,$28.00,$49.83,70.71%
4,"Apr 25, 2024",MRX,Marex Group plc,$19.00,$19.17,0.53%
...,...,...,...,...,...,...
213,"Jan 25, 2023",QSG,QuantaSing Group Ltd,$12.50,$3.16,-74.88%
214,"Jan 20, 2023",CVKD,"Cadrenal Therapeutics, Inc.",$5.00,$0.48,-90.28%
215,"Jan 13, 2023",SKWD,"Skyward Specialty Insurance Group, Inc.",$15.00,$37.61,150.40%
216,"Jan 13, 2023",ISRL,Israel Acquisitions Corp,$10.00,$10.92,9.20%
217,"Jan 13, 2023",MGOL,MGO Global Inc.,$5.00,$0.23,-95.38%

In [ ]:
# convert to datetime
stacked_ipos_df['IPO Date'] = pd.to_datetime(stacked_ipos_df['IPO Date'],format='mixed')
stacked_ipos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   IPO Date      218 non-null    datetime64[ns]
 1   Symbol        218 non-null    object
 2   Company Name  218 non-null    object
 3   IPO Price     218 non-null    object
 4   Current       218 non-null    object
 5   Return        218 non-null    object
dtypes: datetime64[ns](1), object(5)
memory usage: 10.3+ KB

In [ ]:
# Filter data for "IPO date" before March 1, 2024 ("< 2024-03-01")
ipos_Mar2024 = stacked_ipos_df[(stacked_ipos_df['IPO Date'] < '2024-03-01')]
ipos_Mar2024 = ipos_Mar2024.reset_index(drop=True)
ipos_Mar2024

,IPO Date,Symbol,Company Name,IPO Price,Current,Return
0,2024-02-27,SMXT,"SolarMax Technology, Inc.",$4.00,$10.34,167.13%
1,2024-02-22,VHAI,Vocodia Holdings Corp,$4.25,$0.13,-96.89%
2,2024-02-21,DYCQ,DT Cloud Acquisition Corporation,$10.00,$10.16,1.40%
3,2024-02-16,CHRO,Chromocell Therapeutics Corp,$6.00,$1.84,-72.33%
4,2024-02-14,UMAC,"Unusual Machines, Inc.",$4.00,$1.09,-73.50%
...,...,...,...,...,...,...
180,2023-01-25,QSG,QuantaSing Group Ltd,$12.50,$3.16,-74.88%
181,2023-01-20,CVKD,"Cadrenal Therapeutics, Inc.",$5.00,$0.48,-90.28%
182,2023-01-13,SKWD,"Skyward Specialty Insurance Group, Inc.",$15.00,$37.61,150.40%
183,2023-01-13,ISRL,Israel Acquisitions Corp,$10.00,$10.92,9.20%
184,2023-01-13,MGOL,MGO Global Inc.,$5.00,$0.23,-95.38%

In [ ]:
# Drop 'RYZB', as it is no longer available on Yahoo Finance
ipos_184 = ipos_Mar2024[(ipos_Mar2024['Symbol'] != 'RYZB')]
ipos_184 = ipos_184.reset_index(drop=True)
ipos_184

,IPO Date,Symbol,Company Name,IPO Price,Current,Return
0,2024-02-27,SMXT,"SolarMax Technology, Inc.",$4.00,$10.34,167.13%
1,2024-02-22,VHAI,Vocodia Holdings Corp,$4.25,$0.13,-96.89%
2,2024-02-21,DYCQ,DT Cloud Acquisition Corporation,$10.00,$10.16,1.40%
3,2024-02-16,CHRO,Chromocell Therapeutics Corp,$6.00,$1.84,-72.33%
4,2024-02-14,UMAC,"Unusual Machines, Inc.",$4.00,$1.09,-73.50%
...,...,...,...,...,...,...
179,2023-01-25,QSG,QuantaSing Group Ltd,$12.50,$3.16,-74.88%
180,2023-01-20,CVKD,"Cadrenal Therapeutics, Inc.",$5.00,$0.48,-90.28%
181,2023-01-13,SKWD,"Skyward Specialty Insurance Group, Inc.",$15.00,$37.61,150.40%
182,2023-01-13,ISRL,Israel Acquisitions Corp,$10.00,$10.92,9.20%
183,2023-01-13,MGOL,MGO Global Inc.,$5.00,$0.23,-95.38%

In [ ]:
# Get tickers of all 184 stocks
tickers_184 = list(ipos_184['Symbol'])
tickers_184

['SMXT',
 'VHAI',
 'DYCQ',
 'CHRO',
 'UMAC',
 'TBBB',
 'MGX',
 'HLXB',
 'TELO',
 'KYTX',
 'PMNT',
 'AHR',
 'LEGT',
 'ANRO',
 'GUTS',
 'AS',
 'FBLG',
 'BTSG',
 'AVBP',
 'HAO',
 'CGON',
 'YIBO',
 'SUGP',
 'JL',
 'KSPI',
 'JVSA',
 'PSBD',
 'CCTG',
 'SYNX',
 'SDHC',
 'ROMA',
 'IROH',
 'LGCB',
 'ZKH',
 'BAYA',
 'INHD',
 'AFJK',
 'GSIW',
 'FEBO',
 'CLBR',
 'ELAB',
 'RR',
 'DDC',
 'SHIM',
 'GLAC',
 'SGN',
 'HG',
 'CRGX',
 'ANSC',
 'AITR',
 'GVH',
 'LXEO',
 'PAPL',
 'ATGL',
 'MNR',
 'WBUY',
 'NCL',
 'BIRK',
 'GMM',
 'PMEC',
 'LRHC',
 'GPAK',
 'SPKL',
 'QETA',
 'MSS',
 'ANL',
 'SYRA',
 'VSME',
 'LRE',
 'TURB',
 'MDBH',
 'KVYO',
 'CART',
 'DTCK',
 'NMRA',
 'ARM',
 'SPPL',
 'NWGL',
 'SWIN',
 'IVP',
 'NNAG',
 'SRM',
 'SPGC',
 'LQR',
 'NRXS',
 'FTEL',
 'MIRA',
 'PXDT',
 'HRYU',
 'CTNT',
 'SRFM',
 'PRZO',
 'HYAC',
 'KVAC',
 'JNVR',
 'ELWS',
 'WRNT',
 'TSBX',
 'ODD',
 'APGE',
 'NETD',
 'SGMT',
 'BOWN',
 'SXTP',
 'PWM',
 'VTMX',
 'INTS',
 'SVV',
 'KGS',
 'FIHL',
 'GENK',
 'BUJA',
 'BOF',
 'AZTR',
 'CAVA',
 'ESHA',
 'ATMU',
 'ATS',
 'IPXX',
 'CWD',
 'SGE',
 'SLRN',
 'ALCY',
 'KVUE',
 'GODN',
 'TRNR',
 'AACT',
 'JYD',
 'USGO',
 'UCAR',
 'WLGS',
 'TPET',
 'TCJH',
 'GDTC',
 'VCIG',
 'GDHG',
 'ARBB',
 'ISPR',
 'MGIH',
 'MWG',
 'HSHP',
 'SFWL',
 'SYT',
 'HKIT',
 'CHSN',
 'TBMC',
 'HLP',
 'ZJYL',
 'TMTC',
 'YGFGF',
 'OAKU',
 'BANL',
 'OMH',
 'MGRX',
 'FORL',
 'ICG',
 'IZM',
 'AESI',
 'AIXI',
 'SBXC',
 'BMR',
 'DIST',
 'GXAI',
 'MARX',
 'BFRG',
 'ENLT',
 'MLYS',
 'PTHR',
 'BLAC',
 'NXT',
 'HSAI',
 'LSDI',
 'LICN',
 'GPCR',
 'ASST',
 'CETU',
 'TXO',
 'BREA',
 'GNLX',
 'QSG',
 'CVKD',
 'SKWD',
 'ISRL',
 'MGOL']

In [ ]:
# Change symbol name for PTHR to HOVR
index = tickers_184.index('PTHR')
tickers_184[index] = 'HOVR'

In [ ]:
import time

stocks_df = pd.DataFrame({'A' : []})

for i,ticker in enumerate(tickers_184):
  print(i,ticker)

  # Work with stock prices
  historyPrices = yf.download(tickers = ticker,
                     period = "max",
                     interval = "1d")

  # generate features for historical prices, and what we want to predict
  historyPrices['Ticker'] = ticker
  historyPrices['Year']= historyPrices.index.year
  historyPrices['Month'] = historyPrices.index.month
  historyPrices['Weekday'] = historyPrices.index.weekday
  historyPrices['Date'] = historyPrices.index.date

  # historical returns
  for i in range(1,31):
    historyPrices['growth_'+str(i)+'d'] = historyPrices['Adj Close'] / historyPrices['Adj Close'].shift(i)
  historyPrices['growth_future_5d'] = historyPrices['Adj Close'].shift(-5) / historyPrices['Adj Close']

  # Technical indicators
  # SimpleMovingAverage 10 days and 20 days
  historyPrices['SMA10']= historyPrices['Close'].rolling(10).mean()
  historyPrices['SMA20']= historyPrices['Close'].rolling(20).mean()
  historyPrices['growing_moving_average'] = np.where(historyPrices['SMA10'] > historyPrices['SMA20'], 1, 0)
  historyPrices['high_minus_low_relative'] = (historyPrices.High - historyPrices.Low) / historyPrices['Adj Close']

  # 30d rolling volatility : https://ycharts.com/glossary/terms/rolling_vol_30
  historyPrices['volatility'] =   historyPrices['Adj Close'].rolling(30).std() * np.sqrt(252)

  # what we want to predict
  historyPrices['is_positive_growth_5d_future'] = np.where(historyPrices['growth_future_5d'] > 1, 1, 0)

  # sleep 1 sec between downloads - not to overload the API server
  time.sleep(1)


  if stocks_df.empty:
    stocks_df = historyPrices
  else:
    stocks_df = pd.concat([stocks_df, historyPrices], ignore_index=True)

[*********************100%%**********************]  1 of 1 completed

0 SMXT

[*********************100%%**********************]  1 of 1 completed

1 VHAI

[*********************100%%**********************]  1 of 1 completed

2 DYCQ

[*********************100%%**********************]  1 of 1 completed

3 CHRO

[*********************100%%**********************]  1 of 1 completed

4 UMAC

[*********************100%%**********************]  1 of 1 completed

5 TBBB

[*********************100%%**********************]  1 of 1 completed

6 MGX

[*********************100%%**********************]  1 of 1 completed

7 HLXB

[*********************100%%**********************]  1 of 1 completed

8 TELO

[*********************100%%**********************]  1 of 1 completed

9 KYTX

[*********************100%%**********************]  1 of 1 completed

10 PMNT

[*********************100%%**********************]  1 of 1 completed

11 AHR

[*********************100%%**********************]  1 of 1 completed

12 LEGT

[*********************100%%**********************]  1 of 1 completed

13 ANRO

[*********************100%%**********************]  1 of 1 completed

14 GUTS

[*********************100%%**********************]  1 of 1 completed

15 AS

[*********************100%%**********************]  1 of 1 completed

16 FBLG

[*********************100%%**********************]  1 of 1 completed

17 BTSG

[*********************100%%**********************]  1 of 1 completed

18 AVBP

[*********************100%%**********************]  1 of 1 completed

19 HAO

[*********************100%%**********************]  1 of 1 completed

20 CGON

[*********************100%%**********************]  1 of 1 completed

21 YIBO

[*********************100%%**********************]  1 of 1 completed

22 SUGP

[*********************100%%**********************]  1 of 1 completed

23 JL

[*********************100%%**********************]  1 of 1 completed

24 KSPI

[*********************100%%**********************]  1 of 1 completed

25 JVSA

[*********************100%%**********************]  1 of 1 completed

26 PSBD

[*********************100%%**********************]  1 of 1 completed

27 CCTG

[*********************100%%**********************]  1 of 1 completed

28 SYNX

[*********************100%%**********************]  1 of 1 completed

29 SDHC

[*********************100%%**********************]  1 of 1 completed

30 ROMA

[*********************100%%**********************]  1 of 1 completed

31 IROH

[*********************100%%**********************]  1 of 1 completed

32 LGCB

[*********************100%%**********************]  1 of 1 completed

33 ZKH

[*********************100%%**********************]  1 of 1 completed

34 BAYA

[*********************100%%**********************]  1 of 1 completed

35 INHD

[*********************100%%**********************]  1 of 1 completed

36 AFJK

[*********************100%%**********************]  1 of 1 completed

37 GSIW

[*********************100%%**********************]  1 of 1 completed

38 FEBO

[*********************100%%**********************]  1 of 1 completed

39 CLBR

[*********************100%%**********************]  1 of 1 completed

40 ELAB

[*********************100%%**********************]  1 of 1 completed

41 RR

[*********************100%%**********************]  1 of 1 completed

42 DDC

[*********************100%%**********************]  1 of 1 completed

43 SHIM

[*********************100%%**********************]  1 of 1 completed

44 GLAC

[*********************100%%**********************]  1 of 1 completed

45 SGN

[*********************100%%**********************]  1 of 1 completed

46 HG

[*********************100%%**********************]  1 of 1 completed

47 CRGX

[*********************100%%**********************]  1 of 1 completed

48 ANSC

[*********************100%%**********************]  1 of 1 completed

49 AITR

[*********************100%%**********************]  1 of 1 completed

50 GVH

[*********************100%%**********************]  1 of 1 completed

51 LXEO

[*********************100%%**********************]  1 of 1 completed

52 PAPL

[*********************100%%**********************]  1 of 1 completed

53 ATGL

[*********************100%%**********************]  1 of 1 completed

54 MNR

[*********************100%%**********************]  1 of 1 completed

55 WBUY

[*********************100%%**********************]  1 of 1 completed

56 NCL

[*********************100%%**********************]  1 of 1 completed

57 BIRK

[*********************100%%**********************]  1 of 1 completed

58 GMM

[*********************100%%**********************]  1 of 1 completed

59 PMEC

[*********************100%%**********************]  1 of 1 completed

60 LRHC

[*********************100%%**********************]  1 of 1 completed

61 GPAK

[*********************100%%**********************]  1 of 1 completed

62 SPKL

[*********************100%%**********************]  1 of 1 completed

63 QETA

[*********************100%%**********************]  1 of 1 completed

64 MSS

[*********************100%%**********************]  1 of 1 completed

65 ANL

[*********************100%%**********************]  1 of 1 completed

66 SYRA

[*********************100%%**********************]  1 of 1 completed

67 VSME

[*********************100%%**********************]  1 of 1 completed

68 LRE

[*********************100%%**********************]  1 of 1 completed

69 TURB

[*********************100%%**********************]  1 of 1 completed

70 MDBH

[*********************100%%**********************]  1 of 1 completed

71 KVYO

[*********************100%%**********************]  1 of 1 completed

72 CART

[*********************100%%**********************]  1 of 1 completed

73 DTCK

[*********************100%%**********************]  1 of 1 completed

74 NMRA

[*********************100%%**********************]  1 of 1 completed

75 ARM

[*********************100%%**********************]  1 of 1 completed

76 SPPL

[*********************100%%**********************]  1 of 1 completed

77 NWGL

[*********************100%%**********************]  1 of 1 completed

78 SWIN

[*********************100%%**********************]  1 of 1 completed

79 IVP

[*********************100%%**********************]  1 of 1 completed

80 NNAG

[*********************100%%**********************]  1 of 1 completed

81 SRM

[*********************100%%**********************]  1 of 1 completed

82 SPGC

[*********************100%%**********************]  1 of 1 completed

83 LQR

[*********************100%%**********************]  1 of 1 completed

84 NRXS

[*********************100%%**********************]  1 of 1 completed

85 FTEL

[*********************100%%**********************]  1 of 1 completed

86 MIRA

[*********************100%%**********************]  1 of 1 completed

87 PXDT

[*********************100%%**********************]  1 of 1 completed

88 HRYU

[*********************100%%**********************]  1 of 1 completed

89 CTNT

[*********************100%%**********************]  1 of 1 completed

90 SRFM

[*********************100%%**********************]  1 of 1 completed

91 PRZO

[*********************100%%**********************]  1 of 1 completed

92 HYAC

[*********************100%%**********************]  1 of 1 completed

93 KVAC

[*********************100%%**********************]  1 of 1 completed

94 JNVR

[*********************100%%**********************]  1 of 1 completed

95 ELWS

[*********************100%%**********************]  1 of 1 completed

96 WRNT

[*********************100%%**********************]  1 of 1 completed

97 TSBX

[*********************100%%**********************]  1 of 1 completed

98 ODD

[*********************100%%**********************]  1 of 1 completed

99 APGE

[*********************100%%**********************]  1 of 1 completed

100 NETD

[*********************100%%**********************]  1 of 1 completed

101 SGMT

[*********************100%%**********************]  1 of 1 completed

102 BOWN

[*********************100%%**********************]  1 of 1 completed

103 SXTP

[*********************100%%**********************]  1 of 1 completed

104 PWM

[*********************100%%**********************]  1 of 1 completed

105 VTMX

[*********************100%%**********************]  1 of 1 completed

106 INTS

[*********************100%%**********************]  1 of 1 completed

107 SVV

[*********************100%%**********************]  1 of 1 completed

108 KGS

[*********************100%%**********************]  1 of 1 completed

109 FIHL

[*********************100%%**********************]  1 of 1 completed

110 GENK

[*********************100%%**********************]  1 of 1 completed

111 BUJA

[*********************100%%**********************]  1 of 1 completed

112 BOF

[*********************100%%**********************]  1 of 1 completed

113 AZTR

[*********************100%%**********************]  1 of 1 completed

114 CAVA

[*********************100%%**********************]  1 of 1 completed

115 ESHA

[*********************100%%**********************]  1 of 1 completed

116 ATMU

[*********************100%%**********************]  1 of 1 completed

117 ATS

[*********************100%%**********************]  1 of 1 completed

118 IPXX

[*********************100%%**********************]  1 of 1 completed

119 CWD

[*********************100%%**********************]  1 of 1 completed

120 SGE

[*********************100%%**********************]  1 of 1 completed

121 SLRN

[*********************100%%**********************]  1 of 1 completed

122 ALCY

[*********************100%%**********************]  1 of 1 completed

123 KVUE

[*********************100%%**********************]  1 of 1 completed

124 GODN

[*********************100%%**********************]  1 of 1 completed

125 TRNR

[*********************100%%**********************]  1 of 1 completed

126 AACT

[*********************100%%**********************]  1 of 1 completed

127 JYD

[*********************100%%**********************]  1 of 1 completed

128 USGO

[*********************100%%**********************]  1 of 1 completed

129 UCAR

[*********************100%%**********************]  1 of 1 completed

130 WLGS

[*********************100%%**********************]  1 of 1 completed

131 TPET

[*********************100%%**********************]  1 of 1 completed

132 TCJH

[*********************100%%**********************]  1 of 1 completed

133 GDTC

[*********************100%%**********************]  1 of 1 completed

134 VCIG

[*********************100%%**********************]  1 of 1 completed

135 GDHG

[*********************100%%**********************]  1 of 1 completed

136 ARBB

[*********************100%%**********************]  1 of 1 completed

137 ISPR

[*********************100%%**********************]  1 of 1 completed

138 MGIH

[*********************100%%**********************]  1 of 1 completed

139 MWG

[*********************100%%**********************]  1 of 1 completed

140 HSHP

[*********************100%%**********************]  1 of 1 completed

141 SFWL

[*********************100%%**********************]  1 of 1 completed

142 SYT

[*********************100%%**********************]  1 of 1 completed

143 HKIT

[*********************100%%**********************]  1 of 1 completed

144 CHSN

[*********************100%%**********************]  1 of 1 completed

145 TBMC

[*********************100%%**********************]  1 of 1 completed

146 HLP

[*********************100%%**********************]  1 of 1 completed

147 ZJYL

[*********************100%%**********************]  1 of 1 completed

148 TMTC

[*********************100%%**********************]  1 of 1 completed

149 YGFGF

[*********************100%%**********************]  1 of 1 completed

150 OAKU

[*********************100%%**********************]  1 of 1 completed

151 BANL

[*********************100%%**********************]  1 of 1 completed

152 OMH

[*********************100%%**********************]  1 of 1 completed

153 MGRX

[*********************100%%**********************]  1 of 1 completed

154 FORL

[*********************100%%**********************]  1 of 1 completed

155 ICG

[*********************100%%**********************]  1 of 1 completed

156 IZM

[*********************100%%**********************]  1 of 1 completed

157 AESI

[*********************100%%**********************]  1 of 1 completed

158 AIXI

[*********************100%%**********************]  1 of 1 completed

159 SBXC

[*********************100%%**********************]  1 of 1 completed

160 BMR

[*********************100%%**********************]  1 of 1 completed

161 DIST

[*********************100%%**********************]  1 of 1 completed

162 GXAI

[*********************100%%**********************]  1 of 1 completed

163 MARX

[*********************100%%**********************]  1 of 1 completed

164 BFRG

[*********************100%%**********************]  1 of 1 completed

165 ENLT

[*********************100%%**********************]  1 of 1 completed

166 MLYS

[*********************100%%**********************]  1 of 1 completed

167 HOVR

[*********************100%%**********************]  1 of 1 completed

168 BLAC

[*********************100%%**********************]  1 of 1 completed

169 NXT

[*********************100%%**********************]  1 of 1 completed

170 HSAI

[*********************100%%**********************]  1 of 1 completed

171 LSDI

[*********************100%%**********************]  1 of 1 completed

172 LICN

[*********************100%%**********************]  1 of 1 completed

173 GPCR

[*********************100%%**********************]  1 of 1 completed

174 ASST

[*********************100%%**********************]  1 of 1 completed

175 CETU

[*********************100%%**********************]  1 of 1 completed

176 TXO

[*********************100%%**********************]  1 of 1 completed

177 BREA

[*********************100%%**********************]  1 of 1 completed

178 GNLX

[*********************100%%**********************]  1 of 1 completed

179 QSG

[*********************100%%**********************]  1 of 1 completed

180 CVKD

[*********************100%%**********************]  1 of 1 completed

181 SKWD

[*********************100%%**********************]  1 of 1 completed

182 ISRL

[*********************100%%**********************]  1 of 1 completed

183 MGOL

In [ ]:
stocks_df.head(25)

     Open    High     Low  Close  Adj Close   Volume Ticker  Year  Month  Weekday        Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d  growth_8d  growth_9d  growth_10d  growth_11d  growth_12d  growth_13d  growth_14d  growth_15d  growth_16d  growth_17d  growth_18d  growth_19d  growth_20d  growth_21d  growth_22d  growth_23d  growth_24d  growth_25d  growth_26d  growth_27d  growth_28d  growth_29d  growth_30d  growth_future_5d  SMA10   SMA20  growing_moving_average  high_minus_low_relative  volatility  is_positive_growth_5d_future
0    3.50   9.350   3.500   8.00       8.00  2840400   SMXT  2024      2        1  2024-02-27        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          0.657500    NaN     NaN                       0                 0.731250         NaN                             0
1    6.42   7.240   5.600   5.86       5.86   243200   SMXT  2024      2        2  2024-02-28   0.732500        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.225256    NaN     NaN                       0                 0.279863         NaN                             1
2    5.74   5.840   4.300   4.89       4.89   130000   SMXT  2024      2        3  2024-02-29   0.834471   0.611250        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.490798    NaN     NaN                       0                 0.314928         NaN                             1
3    3.94   5.150   3.800   4.88       4.88   485000   SMXT  2024      3        4  2024-03-01   0.997955   0.832765   0.610000        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.450820    NaN     NaN                       0                 0.276639         NaN                             1
4    4.73   5.100   4.258   4.66       4.66   114300   SMXT  2024      3        0  2024-03-04   0.954918   0.952965   0.795222   0.582500        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.866953    NaN     NaN                       0                 0.180687         NaN                             1
5    4.50   5.630   4.400   5.26       5.26   142400   SMXT  2024      3        1  2024-03-05   1.128755   1.077869   1.075665   0.897611   0.657500        NaN        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.456274    NaN     NaN                       0                 0.233840         NaN                             1
6    5.25   7.300   5.250   7.18       7.18   341800   SMXT  2024      3        2  2024-03-06   1.365019   1.540773   1.471311   1.468303   1.225256   0.897500        NaN        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.229805    NaN     NaN                       0                 0.285515         NaN                             1
7    7.53   7.750   6.971   7.29       7.29    94700   SMXT  2024      3        3  2024-03-07   1.015320   1.385931   1.564378   1.493852   1.490798   1.244027   0.911250        NaN        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.052126    NaN     NaN                       0                 0.106859         NaN                             1
8    7.30   7.300   6.840   7.08       7.08    38200   SMXT  2024      3        4  2024-03-08   0.971193   0.986072   1.346008   1.519313   1.450820   1.447853   1.208191   0.885000        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.169492    NaN     NaN                       0                 0.064972         NaN                             1
9    6.97   8.900   6.760   8.70       8.70   132300   SMXT  2024      3        0  2024-03-11   1.228814   1.193416   1.211699   1.653992   1.866953   1.782787   1.779141   1.484642   1.087500         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          0.893103  6.380     NaN                       0                 0.245977         NaN                             0
10   9.50  13.490   6.660   7.66       7.66  1012600   SMXT  2024      3        1  2024-03-12   0.880460   1.081921   1.050754   1.066852   1.456274   1.643777   1.569672   1.566462   1.307167    0.957500         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.018277  6.346     NaN                       0                 0.891645         NaN                             1
11   7.29   9.000   7.050   8.83       8.83   326600   SMXT  2024      3        2  2024-03-13   1.152742   1.014943   1.247175   1.211248   1.229805   1.678707   1.894850   1.809426   1.805726    1.506826    1.103750         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          0.878822  6.643     NaN                       0                 0.220838         NaN                             0
12   8.61   9.000   7.160   7.67       7.67   137500   SMXT  2024      3        3  2024-03-14   0.868630   1.001306   0.881609   1.083333   1.052126   1.068245   1.458175   1.645923   1.571721    1.568507    1.308874    0.958750         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.016949  6.921     NaN                       0                 0.239896         NaN                             1
13   7.95   8.990   7.170   8.28       8.28   106000   SMXT  2024      3        4  2024-03-15   1.079531   0.937712   1.080940   0.951724   1.169492   1.135802   1.153203   1.574144   1.776824    1.696721    1.693252    1.412969    1.035000         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          0.969807  7.261     NaN                       0                 0.219807         NaN                             0
14   8.26   8.740   7.475   7.77       7.77    95800   SMXT  2024      3        0  2024-03-18   0.938406   1.013038   0.879955   1.014360   0.893103   1.097458   1.065844   1.082173   1.477186    1.667382    1.592213    1.588957    1.325939    0.971250         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.033462  7.572     NaN                       0                 0.162806         NaN                             1
15   7.51   8.430   7.510   7.80       7.80   231500   SMXT  2024      3        1  2024-03-19   1.003861   0.942029   1.016949   0.883352   1.018277   0.896552   1.101695   1.069959   1.086351    1.482890    1.673820    1.598361    1.595092    1.331058    0.975000         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.000000  7.826     NaN                       0                 0.117949         NaN                             0
16   7.90   8.560   7.580   7.76       7.76   155700   SMXT  2024      3        2  2024-03-20   0.994872   0.998713   0.937198   1.011734   0.878822   1.013055   0.891954   1.096045   1.064472    1.080780    1.475285    1.665236    1.590164    1.586912    1.324232    0.970000         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.018041  7.884     NaN                       0                 0.126289         NaN                             1
17   7.59   8.522   6.320   7.80       7.80   282900   SMXT  2024      3        3  2024-03-21   1.005155   1.000000   1.003861   0.942029   1.016949   0.883352   1.018277   0.896552   1.101695    1.069959    1.086351    1.482890    1.673820    1.598361    1.595092    1.331058    0.975000         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.173077  7.935     NaN                       0                 0.282308         NaN                             1
18   7.60   8.768   7.600   8.03       8.03   138400   SMXT  2024      3        4  2024-03-22   1.029487   1.034794   1.029487   1.033462   0.969807   1.046936   0.909400   1.048303   0.922988    1.134181    1.101509    1.118384    1.526616    1.723176    1.645492    1.642127    1.370307    1.003750         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.364882  8.030     NaN                       0                 0.145455         NaN                             1
19   8.09   9.710   7.950   8.03       8.03   262500   SMXT  2024      3        0  2024-03-25   1.000000   1.029487   1.034794   1.029487   1.033462   0.969807   1.046936   0.909400   1.048303    0.922988    1.134181    1.101509    1.118384    1.526616    1.723176    1.645492    1.642127    1.370307    1.003750         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.337484  7.963  7.1715                       1                 0.219178         NaN                             1
20   7.84   8.690   7.670   7.80       7.80   161100   SMXT  2024      3        1  2024-03-26   0.971357   0.971357   1.000000   1.005155   1.000000   1.003861   0.942029   1.016949   0.883352    1.018277    0.896552    1.101695    1.069959    1.086351    1.482890    1.673820    1.598361    1.595092    1.331058    0.975000         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.691026  7.977  7.1615                       1                 0.130769         NaN                             1
21   7.79   8.200   7.702   7.90       7.90   302500   SMXT  2024      3        2  2024-03-27   1.012821   0.983811   0.983811   1.012821   1.018041   1.012821   1.016731   0.954106   1.029987    0.894677    1.031332    0.908046    1.115819    1.083676    1.100279    1.501901    1.695279    1.618852    1.615542    1.348123    0.987500         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.459494  7.884  7.2635                       1                 0.063038         NaN                             1
22   8.18   9.475   8.000   9.15       9.15   311900   SMXT  2024      3        3  2024-03-28   1.158228   1.173077   1.139477   1.139477   1.173077   1.179124   1.173077   1.177606   1.105072    1.192960    1.036240    1.194517    1.051724    1.292373    1.255144    1.274373    1.739544    1.963519    1.875000    1.871166    1.561433    1.143750         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.234973  8.032  7.4765                       1                 0.161202         NaN                             1
23   9.35  11.769   9.300  10.96      10.96   477400   SMXT  2024      4        0  2024-04-01   1.197814   1.387342   1.405128   1.364882   1.364882   1.405128   1.412371   1.405128   1.410553    1.323672    1.428944    1.241223    1.430809    1.259770    1.548023    1.503429    1.526462    2.083650    2.351931    2.245902    2.241309    1.870307    1.370000         NaN         NaN         NaN         NaN         NaN         NaN         NaN          1.036496  8.300  7.7805                       1                 0.225274         NaN                             1
24  11.56  11.873  10.500  10.74      10.74   169400   SMXT  2024      4        1  2024-04-02   0.979927   1.173771   1.359494   1.376923   1.337484   1.337484   1.376923   1.384021   1.376923    1.382239    1.297101    1.400261    1.216308    1.402089    1.234483    1.516949    1.473251    1.495822    2.041825    2.304721    2.200820    2.196319    1.832764      1.3425         NaN         NaN         NaN         NaN         NaN         NaN          1.150838  8.597  8.0845                       1                 0.127840         NaN                             1

In [ ]:
# check unique tickers
stocks_df.Ticker.nunique()

184

In [ ]:
# count of observations by stock
stocks_df.Ticker.value_counts()

Ticker
ATS     3613
ENLT     338
SKWD     330
MGOL     330
CVKD     326
        ...
VHAI      51
SMXT      50
JVSA      41
LEGT      28
DYCQ      18
Name: count, Length: 184, dtype: int64

In [ ]:
stocks_min_df = stocks_df.groupby(['Ticker']).Date.agg(['min'])

In [ ]:
stocks_min_df

               min
Ticker
AACT    2023-06-13
AESI    2023-03-09
AFJK    2024-01-23
AHR     2024-02-07
AITR    2024-01-02
AIXI    2023-03-09
ALCY    2023-07-07
ANL     2023-09-29
ANRO    2024-02-02
ANSC    2024-01-03
APGE    2023-07-14
ARBB    2023-04-05
ARM     2023-09-14
AS      2024-02-01
ASST    2023-02-03
ATGL    2023-10-31
ATMU    2023-05-26
ATS     2009-12-29
AVBP    2024-01-26
AZTR    2023-06-20
BANL    2023-03-23
BAYA    2023-12-29
BFRG    2023-02-13
BIRK    2023-10-11
BLAC    2023-03-21
BMR     2023-02-28
BOF     2023-06-16
BOWN    2023-09-05
BREA    2023-01-27
BTSG    2024-01-26
BUJA    2023-09-05
CART    2023-09-19
CAVA    2023-06-16
CCTG    2024-01-18
CETU    2023-03-28
CGON    2024-01-25
CHRO    2024-02-16
CHSN    2023-03-30
CLBR    2024-01-11
CRGX    2023-11-13
CTNT    2023-08-01
CVKD    2023-01-20
CWD     2023-05-18
DDC     2023-11-20
DIST    2023-03-30
DTCK    2023-09-19
DYCQ    2024-04-12
ELAB    2023-11-21
ELWS    2023-07-25
ENLT    2023-01-03
ESHA    2023-06-14
FBLG    2024-02-01
FEBO    2023-11-30
FIHL    2023-06-29
FORL    2023-05-16
FTEL    2023-08-14
GDHG    2023-04-12
GDTC    2023-04-14
GENK    2023-06-28
GLAC    2023-12-04
GMM     2023-10-09
GNLX    2023-01-26
GODN    2023-06-28
GPAK    2023-10-09
GPCR    2023-02-03
GSIW    2023-12-01
GUTS    2024-02-02
GVH     2023-11-08
GXAI    2023-02-15
HAO     2024-01-26
HG      2023-11-13
HKIT    2023-03-31
HLP     2023-03-29
HLXB    2024-02-09
HOVR    2023-04-03
HRYU    2023-08-14
HSAI    2023-02-09
HSHP    2023-03-31
HYAC    2023-09-15
ICG     2023-03-16
INHD    2023-12-14
INTS    2023-06-30
IPXX    2023-07-17
IROH    2024-02-16
ISPR    2023-04-04
ISRL    2023-02-28
IVP     2023-08-30
IZM     2023-03-15
JL      2024-01-24
JNVR    2023-07-25
JVSA    2024-03-11
JYD     2023-04-24
KGS     2023-06-29
KSPI    2024-01-19
KVAC    2023-09-15
KVUE    2023-05-04
KVYO    2023-09-21
KYTX    2024-02-09
LEGT    2024-03-28
LGCB    2023-12-26
LICN    2023-02-06
LQR     2023-08-10
LRE     2023-09-27
LRHC    2023-10-09
LSDI    2023-02-09
LXEO    2023-11-03
MARX    2023-03-15
MDBH    2023-09-21
MGIH    2023-04-04
MGOL    2023-01-13
MGRX    2023-03-21
MGX     2024-02-09
MIRA    2023-08-14
MLYS    2023-02-10
MNR     2023-10-25
MSS     2023-10-05
MWG     2023-04-03
NCL     2023-10-19
NETD    2023-09-05
NMRA    2023-09-14
NNAG    2023-10-09
NRXS    2023-08-09
NWGL    2023-09-12
NXT     2023-02-09
OAKU    2023-05-19
ODD     2023-07-19
OMH     2023-03-22
PAPL    2023-11-01
PMEC    2023-10-09
PMNT    2024-02-08
PRZO    2023-07-27
PSBD    2024-01-18
PWM     2023-07-07
PXDT    2023-08-01
QETA    2023-11-30
QSG     2023-01-25
ROMA    2024-01-09
RR      2023-11-17
SBXC    2023-05-10
SDHC    2024-01-16
SFWL    2023-03-31
SGE     2023-05-16
SGMT    2023-07-17
SGN     2023-11-14
SHIM    2023-11-14
SKWD    2023-01-13
SLRN    2023-05-04
SMXT    2024-02-27
SPGC    2023-08-15
SPKL    2023-11-27
SPPL    2023-09-13
SRFM    2023-07-28
SRM     2023-08-15
SUGP    2024-01-24
SVV     2023-06-29
SWIN    2023-09-07
SXTP    2023-07-12
SYNX    2024-01-12
SYRA    2023-09-29
SYT     2023-03-31
TBBB    2024-02-09
TBMC    2023-05-15
TCJH    2023-04-18
TELO    2024-02-09
TMTC    2023-05-01
TPET    2023-04-18
TRNR    2023-05-01
TSBX    2023-07-21
TURB    2023-09-22
TXO     2023-01-27
UCAR    2023-04-20
UMAC    2024-02-14
USGO    2023-04-20
VCIG    2023-04-13
VHAI    2024-02-26
VSME    2023-09-27
VTMX    2023-06-30
WBUY    2023-10-19
WLGS    2023-04-20
WRNT    2023-07-25
YGFGF   2023-03-28
YIBO    2024-01-25
ZJYL    2023-03-28
ZKH     2023-12-15

In [ ]:
# Merge df with min_dates
merged_df = pd.merge(stocks_df.reset_index(), stocks_min_df, how='inner', on='Ticker')
merged_df.head()

,index,Open,High,Low,Close,Adj Close,Volume,Ticker,Year,Month,...,growth_29d,growth_30d,growth_future_5d,SMA10,SMA20,growing_moving_average,high_minus_low_relative,volatility,is_positive_growth_5d_future,min
0,0,3.50,9.35,3.500,8.00,8.00,2840400,SMXT,2024,2,...,NaN,NaN,0.657500,NaN,NaN,0,0.731250,NaN,0,2024-02-27
1,1,6.42,7.24,5.600,5.86,5.86,243200,SMXT,2024,2,...,NaN,NaN,1.225256,NaN,NaN,0,0.279863,NaN,1,2024-02-27
2,2,5.74,5.84,4.300,4.89,4.89,130000,SMXT,2024,2,...,NaN,NaN,1.490798,NaN,NaN,0,0.314928,NaN,1,2024-02-27
3,3,3.94,5.15,3.800,4.88,4.88,485000,SMXT,2024,3,...,NaN,NaN,1.450820,NaN,NaN,0,0.276639,NaN,1,2024-02-27
4,4,4.73,5.10,4.258,4.66,4.66,114300,SMXT,2024,3,...,NaN,NaN,1.866953,NaN,NaN,0,0.180687,NaN,1,2024-02-27

In [ ]:
merged_df.describe()

              index          Open          High           Low         Close     Adj Close        Volume          Year         Month       Weekday     growth_1d     growth_2d     growth_3d     growth_4d     growth_5d     growth_6d     growth_7d     growth_8d     growth_9d    growth_10d    growth_11d    growth_12d    growth_13d    growth_14d    growth_15d    growth_16d    growth_17d    growth_18d    growth_19d    growth_20d    growth_21d    growth_22d    growth_23d    growth_24d    growth_25d    growth_26d    growth_27d    growth_28d    growth_29d    growth_30d  growth_future_5d         SMA10         SMA20  growing_moving_average  high_minus_low_relative    volatility  is_positive_growth_5d_future
count  37758.000000  37758.000000  37758.000000  37758.000000  37758.000000  37758.000000  3.775800e+04  37758.000000  37758.000000  37758.000000  37574.000000  37390.000000  37206.000000  37022.000000  36838.000000  36654.000000  36470.000000  36286.000000  36102.000000  35918.000000  35734.000000  35550.000000  35366.000000  35182.000000  34998.000000  34814.000000  34630.000000  34446.000000  34263.000000  34080.000000  33897.000000  33714.000000  33531.000000  33348.000000  33165.000000  32982.000000  32799.000000  32616.000000  32434.000000  32252.000000      36838.000000  36102.000000  34263.000000            37758.000000             37758.000000  32434.000000                  37758.000000
mean   18878.500000     12.239590     12.843654     11.797813     12.219836     12.192457  6.725382e+05   2022.799619      6.003284      2.030722      0.999595      0.999446      0.999348      0.999201      0.999187      0.999216      0.999060      0.998937      0.998841      0.998713      0.998496      0.998051      0.997382      0.996645      0.996012      0.995479      0.995004      0.994656      0.994456      0.994232      0.993878      0.993562      0.993076      0.992633      0.992256      0.992081      0.991923      0.991697      0.991501      0.991428          0.999187     12.131172     12.161255                0.435616                 0.082824     19.637161                      0.452593
std    10899.940069     37.736884     56.559088     32.551052     40.414396     40.403030  5.151531e+06      2.416834      3.617104      1.395819      0.095718      0.135129      0.166115      0.190735      0.215038      0.239514      0.257357      0.275709      0.294642      0.312226      0.326644      0.339122      0.348997      0.358141      0.368098      0.379154      0.390000      0.400144      0.410955      0.421759      0.431590      0.442049      0.451847      0.460721      0.471058      0.484724      0.498423      0.515254      0.534685      0.556971          0.215038     33.795658     33.749086                0.495844                 0.280331    123.569653                      0.497754
min        0.000000      0.002000      0.002000      0.002000      0.002000      0.002000  0.000000e+00   2009.000000      1.000000      0.000000      0.028674      0.003584      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729      0.002729          0.002729      0.002000      0.002000                0.000000                 0.000000      0.000000                      0.000000
25%     9439.250000      1.850000      1.950000      1.736250      1.830000      1.830000  6.100000e+03   2023.000000      3.000000      1.000000      0.977580      0.966452      0.957566      0.949495      0.941844      0.934282      0.927452      0.920792      0.913799      0.907105      0.900896      0.895062      0.889004      0.882506      0.875294      0.869269      0.862966      0.856511      0.851723      0.846532      0.840399      0.835646      0.830742      0.823872      0.820477      0.813817      0.810773      0.806734      0.802721      0.798599          0.941844      1.831000      1.840350                0.000000                 0.012396      1.657686                      0.000000
50%    18878.500000      7.900000      8.186000      7.570000      7.850000      7.850000  5.110000e+04   2023.000000      5.000000      2.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      0.999952      0.999057      0.999038      0.998925      0.998318      0.998033      0.997788      0.997319      0.997170      0.996768      0.996785      0.996209      0.996094      0.995568      0.995587      0.994735      0.994318      0.994260      0.993828      0.993742          1.000000      7.911200      7.985000                0.000000                 0.056088      5.401026                      0.000000
75%    28317.750000     11.990000     12.300000     11.498750     11.937500     11.930000  2.264000e+05   2024.000000      9.000000      3.000000      1.014815      1.020116      1.025118      1.028169      1.031661      1.033784      1.035673      1.038710      1.040186      1.042368      1.043165      1.044217      1.045604      1.046392      1.047993      1.049273      1.051187      1.052336      1.053625      1.055149      1.056911      1.058120      1.058562      1.059736      1.060071      1.059457      1.062052      1.063830      1.065714      1.066667          1.031661     11.884750     11.870375                1.000000                 0.106039     14.787634                      1.000000
max    37757.000000   3069.000000   7500.000000    875.000000   4318.000000   4318.000000  3.723413e+08   2024.000000     12.000000      4.000000      6.826923      6.971311      7.625593      8.650538      8.952632     10.309092     10.183544     10.380646      9.464706      9.105319      9.354651      9.634731     10.380646     11.330986     10.585527     10.740988     11.411348     11.096551     10.726667     11.575540     12.634409     11.491442     12.486842     12.284789     12.661000     15.025219     14.782093     19.655310     22.918785     27.198465          8.952632    944.050000    732.050000                1.000000                42.812496  11364.080129                      1.000000

From the stats, it can be seen that 75% quantile growth is highest for 30 days holding.

**Question 3: Is Growth Concentrated in the Largest Stocks?**

Get the share of days (percentage as int) when Large Stocks outperform (growth_7d - growth over 7 periods back) the Largest stocks?

In [ ]:
US_STOCKS = ['MSFT', 'AAPL', 'GOOG', 'NVDA', 'AMZN', 'META', 'BRK-B', 'LLY', 'AVGO','V', 'JPM']

EU_STOCKS = ['NVO','MC.PA', 'ASML', 'RMS.PA', 'OR.PA', 'SAP', 'ACN', 'TTE', 'SIE.DE','IDEXY','CDI.PA']

INDIA_STOCKS = ['RELIANCE.NS','TCS.NS','HDB','BHARTIARTL.NS','IBN','SBIN.NS','LICI.NS','INFY','ITC.NS','HINDUNILVR.NS','LT.NS']

LARGEST_STOCKS = US_STOCKS + EU_STOCKS + INDIA_STOCKS

In [ ]:
LARGEST_STOCKS

['MSFT',
 'AAPL',
 'GOOG',
 'NVDA',
 'AMZN',
 'META',
 'BRK-B',
 'LLY',
 'AVGO',
 'V',
 'JPM',
 'NVO',
 'MC.PA',
 'ASML',
 'RMS.PA',
 'OR.PA',
 'SAP',
 'ACN',
 'TTE',
 'SIE.DE',
 'IDEXY',
 'CDI.PA',
 'RELIANCE.NS',
 'TCS.NS',
 'HDB',
 'BHARTIARTL.NS',
 'IBN',
 'SBIN.NS',
 'LICI.NS',
 'INFY',
 'ITC.NS',
 'HINDUNILVR.NS',
 'LT.NS']

In [ ]:
import time

stocks_df = pd.DataFrame({'A' : []})

for i,ticker in enumerate(LARGEST_STOCKS):
  print(i,ticker)

  # Work with stock prices
  historyPrices = yf.download(tickers = ticker,
                     start = '2013-12-19',
                     end = '2023-12-31',
                     interval = "1d")

  # generate features for historical prices, and what we want to predict
  historyPrices['Ticker'] = ticker
  historyPrices['Year']= historyPrices.index.year
  historyPrices['Month'] = historyPrices.index.month
  historyPrices['Weekday'] = historyPrices.index.weekday
  historyPrices['Date'] = historyPrices.index.date

  # historical returns
  for i in [1,2,3,4,5,6,7]:
    historyPrices['growth_'+str(i)+'d'] = historyPrices['Adj Close'] / historyPrices['Adj Close'].shift(i)

  # sleep 1 sec between downloads - not to overload the API server
  time.sleep(1)


  if stocks_df.empty:
    stocks_df = historyPrices
  else:
    stocks_df = pd.concat([stocks_df, historyPrices], ignore_index=True)

[*********************100%%**********************]  1 of 1 completed

0 MSFT

[*********************100%%**********************]  1 of 1 completed

1 AAPL

[*********************100%%**********************]  1 of 1 completed

2 GOOG

[*********************100%%**********************]  1 of 1 completed

3 NVDA

[*********************100%%**********************]  1 of 1 completed

4 AMZN

[*********************100%%**********************]  1 of 1 completed

5 META

[*********************100%%**********************]  1 of 1 completed

6 BRK-B

7 LLY

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

8 AVGO

[*********************100%%**********************]  1 of 1 completed

9 V

[*********************100%%**********************]  1 of 1 completed

10 JPM

[*********************100%%**********************]  1 of 1 completed

11 NVO

[*********************100%%**********************]  1 of 1 completed

12 MC.PA

[*********************100%%**********************]  1 of 1 completed

13 ASML

[*********************100%%**********************]  1 of 1 completed

14 RMS.PA

[*********************100%%**********************]  1 of 1 completed

15 OR.PA

[*********************100%%**********************]  1 of 1 completed

16 SAP

[*********************100%%**********************]  1 of 1 completed

17 ACN

[*********************100%%**********************]  1 of 1 completed

18 TTE

[*********************100%%**********************]  1 of 1 completed

19 SIE.DE

[*********************100%%**********************]  1 of 1 completed

20 IDEXY

[*********************100%%**********************]  1 of 1 completed

21 CDI.PA

[*********************100%%**********************]  1 of 1 completed

22 RELIANCE.NS

[*********************100%%**********************]  1 of 1 completed

23 TCS.NS

[*********************100%%**********************]  1 of 1 completed

24 HDB

[*********************100%%**********************]  1 of 1 completed

25 BHARTIARTL.NS

[*********************100%%**********************]  1 of 1 completed

26 IBN

[*********************100%%**********************]  1 of 1 completed

27 SBIN.NS

[*********************100%%**********************]  1 of 1 completed

28 LICI.NS

[*********************100%%**********************]  1 of 1 completed

29 INFY

[*********************100%%**********************]  1 of 1 completed

30 ITC.NS

[*********************100%%**********************]  1 of 1 completed

31 HINDUNILVR.NS

[*********************100%%**********************]  1 of 1 completed

32 LT.NS

In [ ]:
stocks_df

              Open         High          Low        Close    Adj Close    Volume Ticker  Year  Month  Weekday        Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d
0        36.509998    36.549999    36.080002    36.250000    30.468204  34160100   MSFT  2013     12        3  2013-12-19        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1        36.200001    36.930000    36.189999    36.799999    30.930485  62649100   MSFT  2013     12        4  2013-12-20   1.015173        NaN        NaN        NaN        NaN        NaN        NaN
2        36.810001    36.889999    36.549999    36.619999    30.779186  25128700   MSFT  2013     12        0  2013-12-23   0.995108   1.010207        NaN        NaN        NaN        NaN        NaN
3        36.720001    37.169998    36.639999    37.080002    31.165819  14243000   MSFT  2013     12        1  2013-12-24   1.012562   1.007608   1.022896        NaN        NaN        NaN        NaN
4        37.200001    37.490002    37.169998    37.439999    31.468399  17612800   MSFT  2013     12        3  2013-12-26   1.009709   1.022392   1.017391   1.032827        NaN        NaN        NaN
...            ...          ...          ...          ...          ...       ...    ...   ...    ...      ...         ...        ...        ...        ...        ...        ...        ...        ...
81006  3424.000000  3496.000000  3408.600098  3477.949951  3477.949951   1681707  LT.NS  2023     12        4  2023-12-22   1.015712   1.017391   0.993998   0.996091   0.997119   1.013064   1.022987
81007  3477.949951  3508.350098  3477.949951  3490.050049  3490.050049   1072263  LT.NS  2023     12        1  2023-12-26   1.003479   1.019246   1.020930   0.997456   0.999556   1.000588   1.016588
81008  3510.000000  3549.000000  3504.149902  3544.000000  3544.000000   1389266  LT.NS  2023     12        2  2023-12-27   1.015458   1.018991   1.035001   1.036712   1.012875   1.015007   1.016055
81009  3545.000000  3559.949951  3500.500000  3518.050049  3518.050049   3371121  LT.NS  2023     12        3  2023-12-28   0.992678   1.008023   1.011530   1.027423   1.029121   1.005459   1.007575
81010  3531.000000  3540.000000  3495.000000  3526.000000  3526.000000    968577  LT.NS  2023     12        4  2023-12-29   1.002260   0.994921   1.010301   1.013816   1.029745   1.031447   1.007731

[81011 rows x 18 columns]

In [ ]:
# convert to datetime
stocks_df['Date'] = pd.to_datetime(stocks_df['Date'],format='mixed')
stocks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81011 entries, 0 to 81010
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       81011 non-null  float64
 1   High       81011 non-null  float64
 2   Low        81011 non-null  float64
 3   Close      81011 non-null  float64
 4   Adj Close  81011 non-null  float64
 5   Volume     81011 non-null  int64
 6   Ticker     81011 non-null  object
 7   Year       81011 non-null  int32
 8   Month      81011 non-null  int32
 9   Weekday    81011 non-null  int32
 10  Date       81011 non-null  datetime64[ns]
 11  growth_1d  80978 non-null  float64
 12  growth_2d  80945 non-null  float64
 13  growth_3d  80912 non-null  float64
 14  growth_4d  80879 non-null  float64
 15  growth_5d  80846 non-null  float64
 16  growth_6d  80813 non-null  float64
 17  growth_7d  80780 non-null  float64
dtypes: datetime64[ns](1), float64(12), int32(3), int64(1), object(1)
memory usage: 10.2+ MB

In [ ]:
# Filter to contain data only from 2014-01-01
stocks_largest_df = stocks_df[(stocks_df['Date'] >= '2014-01-01')]
stocks_largest_df = stocks_largest_df.reset_index(drop=True)
stocks_largest_df

              Open         High          Low        Close    Adj Close    Volume Ticker  Year  Month  Weekday       Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d
0        37.349998    37.400002    37.099998    37.160000    31.233072  30632200   MSFT  2014      1        3 2014-01-02   0.993318   0.996514   0.996514   0.992522   1.002158   1.014747   1.009783
1        37.200001    37.220001    36.599998    36.910000    31.022942  31134800   MSFT  2014      1        4 2014-01-03   0.993272   0.986635   0.989810   0.989810   0.985844   0.995416   1.007919
2        36.849998    36.889999    36.110001    36.130001    30.367355  43603700   MSFT  2014      1        0 2014-01-06   0.978868   0.972282   0.965785   0.968893   0.968893   0.965011   0.974380
3        36.330002    36.490002    36.209999    36.410000    30.602686  35802800   MSFT  2014      1        1 2014-01-07   1.007749   0.986453   0.979817   0.973269   0.976401   0.976401   0.972489
4        36.000000    36.139999    35.580002    35.759998    30.056355  59971700   MSFT  2014      1        2 2014-01-08   0.982148   0.989759   0.968843   0.962325   0.955894   0.958970   0.958970
...            ...          ...          ...          ...          ...       ...    ...   ...    ...      ...        ...        ...        ...        ...        ...        ...        ...        ...
80757  3424.000000  3496.000000  3408.600098  3477.949951  3477.949951   1681707  LT.NS  2023     12        4 2023-12-22   1.015712   1.017391   0.993998   0.996091   0.997119   1.013064   1.022987
80758  3477.949951  3508.350098  3477.949951  3490.050049  3490.050049   1072263  LT.NS  2023     12        1 2023-12-26   1.003479   1.019246   1.020930   0.997456   0.999556   1.000588   1.016588
80759  3510.000000  3549.000000  3504.149902  3544.000000  3544.000000   1389266  LT.NS  2023     12        2 2023-12-27   1.015458   1.018991   1.035001   1.036712   1.012875   1.015007   1.016055
80760  3545.000000  3559.949951  3500.500000  3518.050049  3518.050049   3371121  LT.NS  2023     12        3 2023-12-28   0.992678   1.008023   1.011530   1.027423   1.029121   1.005459   1.007575
80761  3531.000000  3540.000000  3495.000000  3526.000000  3526.000000    968577  LT.NS  2023     12        4 2023-12-29   1.002260   0.994921   1.010301   1.013816   1.029745   1.031447   1.007731

[80762 rows x 18 columns]

In [ ]:
NEW_US = ['TSLA','WMT','XOM','UNH','MA','PG','JNJ','MRK','HD','COST','ORCL']

NEW_EU = ['PRX.AS','CDI.PA','AIR.PA','SU.PA','ETN','SNY','BUD','DTE.DE','ALV.DE','MDT','AI.PA','EL.PA']

NEW_INDIA = ['BAJFINANCE.NS','MARUTI.NS','HCLTECH.NS','TATAMOTORS.NS','SUNPHARMA.NS','ONGC.NS','ADANIENT.NS','ADANIENT.NS','NTPC.NS','KOTAKBANK.NS','TITAN.NS']

LARGE_STOCKS = NEW_EU + NEW_US + NEW_INDIA

In [ ]:
LARGE_STOCKS

['PRX.AS',
 'CDI.PA',
 'AIR.PA',
 'SU.PA',
 'ETN',
 'SNY',
 'BUD',
 'DTE.DE',
 'ALV.DE',
 'MDT',
 'AI.PA',
 'EL.PA',
 'TSLA',
 'WMT',
 'XOM',
 'UNH',
 'MA',
 'PG',
 'JNJ',
 'MRK',
 'HD',
 'COST',
 'ORCL',
 'BAJFINANCE.NS',
 'MARUTI.NS',
 'HCLTECH.NS',
 'TATAMOTORS.NS',
 'SUNPHARMA.NS',
 'ONGC.NS',
 'ADANIENT.NS',
 'ADANIENT.NS',
 'NTPC.NS',
 'KOTAKBANK.NS',
 'TITAN.NS']

In [ ]:
import time

stocks_large_df = pd.DataFrame({'A' : []})

for i,ticker in enumerate(LARGE_STOCKS):
  print(i,ticker)

  # Work with stock prices
  historyPrices = yf.download(tickers = ticker,
                     start = '2013-12-19',
                     end = '2023-12-31',
                     interval = "1d")

  # generate features for historical prices, and what we want to predict
  historyPrices['Ticker'] = ticker
  historyPrices['Year']= historyPrices.index.year
  historyPrices['Month'] = historyPrices.index.month
  historyPrices['Weekday'] = historyPrices.index.weekday
  historyPrices['Date'] = historyPrices.index.date

  # historical returns
  for i in [1,2,3,4,5,6,7]:
    historyPrices['growth_'+str(i)+'d'] = historyPrices['Adj Close'] / historyPrices['Adj Close'].shift(i)

  # sleep 1 sec between downloads - not to overload the API server
  time.sleep(1)


  if stocks_large_df.empty:
    stocks_large_df = historyPrices
  else:
    stocks_large_df = pd.concat([stocks_large_df, historyPrices], ignore_index=True)

[*********************100%%**********************]  1 of 1 completed

0 PRX.AS

[*********************100%%**********************]  1 of 1 completed

1 CDI.PA

[*********************100%%**********************]  1 of 1 completed

2 AIR.PA

[*********************100%%**********************]  1 of 1 completed

3 SU.PA

[*********************100%%**********************]  1 of 1 completed

4 ETN

[*********************100%%**********************]  1 of 1 completed

5 SNY

[*********************100%%**********************]  1 of 1 completed

6 BUD

[*********************100%%**********************]  1 of 1 completed

7 DTE.DE

8 ALV.DE

[*********************100%%**********************]  1 of 1 completed

9 MDT

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

10 AI.PA

[*********************100%%**********************]  1 of 1 completed

11 EL.PA

[*********************100%%**********************]  1 of 1 completed

12 TSLA

[*********************100%%**********************]  1 of 1 completed

13 WMT

[*********************100%%**********************]  1 of 1 completed

14 XOM

15 UNH

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

16 MA

17 PG

[*********************100%%**********************]  1 of 1 completed

18 JNJ

[*********************100%%**********************]  1 of 1 completed

19 MRK

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

20 HD

[*********************100%%**********************]  1 of 1 completed

21 COST

[*********************100%%**********************]  1 of 1 completed

22 ORCL

[*********************100%%**********************]  1 of 1 completed

23 BAJFINANCE.NS

24 MARUTI.NS

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

25 HCLTECH.NS

[*********************100%%**********************]  1 of 1 completed

26 TATAMOTORS.NS

[*********************100%%**********************]  1 of 1 completed

27 SUNPHARMA.NS

[*********************100%%**********************]  1 of 1 completed

28 ONGC.NS

[*********************100%%**********************]  1 of 1 completed

29 ADANIENT.NS

[*********************100%%**********************]  1 of 1 completed

30 ADANIENT.NS

[*********************100%%**********************]  1 of 1 completed

31 NTPC.NS

[*********************100%%**********************]  1 of 1 completed

32 KOTAKBANK.NS

[*********************100%%**********************]  1 of 1 completed

33 TITAN.NS

In [ ]:
stocks_large_df

              Open         High          Low        Close    Adj Close    Volume    Ticker  Year  Month  Weekday        Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d
0        34.868782    35.511101    33.207928    34.038357    33.763882  14787563    PRX.AS  2019      9        2  2019-09-11        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1        34.501743    34.524685    32.978527    33.148285    32.880985   5842906    PRX.AS  2019      9        3  2019-09-12   0.973851        NaN        NaN        NaN        NaN        NaN        NaN
2        33.171223    34.042942    32.804184    33.905304    33.631901   5068221    PRX.AS  2019      9        4  2019-09-13   1.022837   0.996091        NaN        NaN        NaN        NaN        NaN
3        33.515324    33.721783    32.340797    32.340797    32.080009  49689045    PRX.AS  2019      9        0  2019-09-16   0.953857   0.975640   0.950128        NaN        NaN        NaN        NaN
4        32.758305    33.033585    31.574600    31.794825    31.538437  10523710    PRX.AS  2019      9        1  2019-09-17   0.983118   0.937754   0.959169   0.934088        NaN        NaN        NaN
...            ...          ...          ...          ...          ...       ...       ...   ...    ...      ...         ...        ...        ...        ...        ...        ...        ...        ...
84093  3580.000000  3638.449951  3560.550049  3627.350098  3627.350098    777099  TITAN.NS  2023     12        4  2023-12-22   1.013226   1.020610   1.004681   1.002141   1.007443   1.010010   1.006940
84094  3635.000000  3665.000000  3623.449951  3656.699951  3656.699951    526101  TITAN.NS  2023     12        1  2023-12-26   1.008091   1.021425   1.028868   1.012810   1.010250   1.015595   1.018182
84095  3668.000000  3695.000000  3645.000000  3689.250000  3689.250000    666625  TITAN.NS  2023     12        2  2023-12-27   1.008901   1.017065   1.030517   1.038026   1.021826   1.019242   1.024635
84096  3699.899902  3737.000000  3680.699951  3715.100098  3715.100098   1033648  TITAN.NS  2023     12        3  2023-12-28   1.007007   1.015971   1.024191   1.037737   1.045300   1.028985   1.026384
84097  3715.100098  3715.100098  3660.250000  3675.449951  3675.449951    709614  TITAN.NS  2023     12        4  2023-12-29   0.989327   0.996259   1.005128   1.013260   1.026662   1.034144   1.018003

[84098 rows x 18 columns]

In [ ]:
# convert to datetime
stocks_large_df['Date'] = pd.to_datetime(stocks_large_df['Date'],format='mixed')
stocks_large_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84098 entries, 0 to 84097
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       84098 non-null  float64
 1   High       84098 non-null  float64
 2   Low        84098 non-null  float64
 3   Close      84098 non-null  float64
 4   Adj Close  84098 non-null  float64
 5   Volume     84098 non-null  int64
 6   Ticker     84098 non-null  object
 7   Year       84098 non-null  int32
 8   Month      84098 non-null  int32
 9   Weekday    84098 non-null  int32
 10  Date       84098 non-null  datetime64[ns]
 11  growth_1d  84064 non-null  float64
 12  growth_2d  84030 non-null  float64
 13  growth_3d  83996 non-null  float64
 14  growth_4d  83962 non-null  float64
 15  growth_5d  83928 non-null  float64
 16  growth_6d  83894 non-null  float64
 17  growth_7d  83860 non-null  float64
dtypes: datetime64[ns](1), float64(12), int32(3), int64(1), object(1)
memory usage: 10.6+ MB

In [ ]:
# Filter to contain data only from 2014-01-01
stocks_large_df = stocks_large_df[(stocks_large_df['Date'] >= '2014-01-01')]
stocks_large_df = stocks_large_df.reset_index(drop=True)
stocks_large_df

              Open         High          Low        Close    Adj Close    Volume    Ticker  Year  Month  Weekday       Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d
0        34.868782    35.511101    33.207928    34.038357    33.763882  14787563    PRX.AS  2019      9        2 2019-09-11        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1        34.501743    34.524685    32.978527    33.148285    32.880985   5842906    PRX.AS  2019      9        3 2019-09-12   0.973851        NaN        NaN        NaN        NaN        NaN        NaN
2        33.171223    34.042942    32.804184    33.905304    33.631901   5068221    PRX.AS  2019      9        4 2019-09-13   1.022837   0.996091        NaN        NaN        NaN        NaN        NaN
3        33.515324    33.721783    32.340797    32.340797    32.080009  49689045    PRX.AS  2019      9        0 2019-09-16   0.953857   0.975640   0.950128        NaN        NaN        NaN        NaN
4        32.758305    33.033585    31.574600    31.794825    31.538437  10523710    PRX.AS  2019      9        1 2019-09-17   0.983118   0.937754   0.959169   0.934088        NaN        NaN        NaN
...            ...          ...          ...          ...          ...       ...       ...   ...    ...      ...        ...        ...        ...        ...        ...        ...        ...        ...
83840  3580.000000  3638.449951  3560.550049  3627.350098  3627.350098    777099  TITAN.NS  2023     12        4 2023-12-22   1.013226   1.020610   1.004681   1.002141   1.007443   1.010010   1.006940
83841  3635.000000  3665.000000  3623.449951  3656.699951  3656.699951    526101  TITAN.NS  2023     12        1 2023-12-26   1.008091   1.021425   1.028868   1.012810   1.010250   1.015595   1.018182
83842  3668.000000  3695.000000  3645.000000  3689.250000  3689.250000    666625  TITAN.NS  2023     12        2 2023-12-27   1.008901   1.017065   1.030517   1.038026   1.021826   1.019242   1.024635
83843  3699.899902  3737.000000  3680.699951  3715.100098  3715.100098   1033648  TITAN.NS  2023     12        3 2023-12-28   1.007007   1.015971   1.024191   1.037737   1.045300   1.028985   1.026384
83844  3715.100098  3715.100098  3660.250000  3675.449951  3675.449951    709614  TITAN.NS  2023     12        4 2023-12-29   0.989327   0.996259   1.005128   1.013260   1.026662   1.034144   1.018003

[83845 rows x 18 columns]

In [ ]:
# Check unique days(trading days) in Largest dataframe
stocks_largest_df['Date'].nunique()

2595

In [ ]:
# Check unique days(trading days) in Large dataframe
stocks_large_df['Date'].nunique()

2595

In [ ]:
# Add ticker category to both dataframes
stocks_largest_df['ticker_category'] = 'LARGEST'
stocks_large_df['ticker_category'] = 'LARGE'

In [ ]:
# Concatenating both the Largest and Large dataframes
merged_ll_df = pd.concat([stocks_largest_df, stocks_large_df])
merged_ll_df

              Open         High          Low        Close    Adj Close    Volume    Ticker  Year  Month  Weekday       Date  growth_1d  growth_2d  growth_3d  growth_4d  growth_5d  growth_6d  growth_7d ticker_category
0        37.349998    37.400002    37.099998    37.160000    31.233072  30632200      MSFT  2014      1        3 2014-01-02   0.993318   0.996514   0.996514   0.992522   1.002158   1.014747   1.009783         LARGEST
1        37.200001    37.220001    36.599998    36.910000    31.022942  31134800      MSFT  2014      1        4 2014-01-03   0.993272   0.986635   0.989810   0.989810   0.985844   0.995416   1.007919         LARGEST
2        36.849998    36.889999    36.110001    36.130001    30.367355  43603700      MSFT  2014      1        0 2014-01-06   0.978868   0.972282   0.965785   0.968893   0.968893   0.965011   0.974380         LARGEST
3        36.330002    36.490002    36.209999    36.410000    30.602686  35802800      MSFT  2014      1        1 2014-01-07   1.007749   0.986453   0.979817   0.973269   0.976401   0.976401   0.972489         LARGEST
4        36.000000    36.139999    35.580002    35.759998    30.056355  59971700      MSFT  2014      1        2 2014-01-08   0.982148   0.989759   0.968843   0.962325   0.955894   0.958970   0.958970         LARGEST
...            ...          ...          ...          ...          ...       ...       ...   ...    ...      ...        ...        ...        ...        ...        ...        ...        ...        ...             ...
83840  3580.000000  3638.449951  3560.550049  3627.350098  3627.350098    777099  TITAN.NS  2023     12        4 2023-12-22   1.013226   1.020610   1.004681   1.002141   1.007443   1.010010   1.006940           LARGE
83841  3635.000000  3665.000000  3623.449951  3656.699951  3656.699951    526101  TITAN.NS  2023     12        1 2023-12-26   1.008091   1.021425   1.028868   1.012810   1.010250   1.015595   1.018182           LARGE
83842  3668.000000  3695.000000  3645.000000  3689.250000  3689.250000    666625  TITAN.NS  2023     12        2 2023-12-27   1.008901   1.017065   1.030517   1.038026   1.021826   1.019242   1.024635           LARGE
83843  3699.899902  3737.000000  3680.699951  3715.100098  3715.100098   1033648  TITAN.NS  2023     12        3 2023-12-28   1.007007   1.015971   1.024191   1.037737   1.045300   1.028985   1.026384           LARGE
83844  3715.100098  3715.100098  3660.250000  3675.449951  3675.449951    709614  TITAN.NS  2023     12        4 2023-12-29   0.989327   0.996259   1.005128   1.013260   1.026662   1.034144   1.018003           LARGE

[164607 rows x 19 columns]

In [ ]:
merged_ll_df.shape

(164607, 19)

In [ ]:
# Calculate average daily growth_7d for the LARGEST_STOCKS group vs. the LARGE_STOCKS
growth7d_mean = pd.DataFrame(merged_ll_df.groupby(by=['Date','ticker_category']).growth_7d.mean())
growth7d_mean

                            growth_7d
Date       ticker_category
2014-01-01 LARGE             1.011684
           LARGEST           1.011797
2014-01-02 LARGE             1.000970
           LARGEST           1.005148
2014-01-03 LARGE             0.999534
...                               ...
2023-12-27 LARGEST           1.014155
2023-12-28 LARGE             0.998583
           LARGEST           1.008533
2023-12-29 LARGE             0.999313
           LARGEST           1.005337

[5190 rows x 1 columns]

In [ ]:
# Pivot the DataFrame
pivot_df = growth7d_mean.pivot_table(index='Date', columns='ticker_category', values='growth_7d')
print(pivot_df)

ticker_category     LARGE   LARGEST
Date
2014-01-01       1.011684  1.011797
2014-01-02       1.000970  1.005148
2014-01-03       0.999534  0.997668
2014-01-06       0.995983  0.994203
2014-01-07       0.991592  0.992509
...                   ...       ...
2023-12-22       1.003014  1.013788
2023-12-26       1.013505  1.014900
2023-12-27       1.002167  1.014155
2023-12-28       0.998583  1.008533
2023-12-29       0.999313  1.005337

[2595 rows x 2 columns]

In [ ]:
# Calculate the number of days when 'LARGE' outperforms 'LARGEST'
outperform_days = (pivot_df['LARGE'] > pivot_df['LARGEST']).sum()

# Total number of trading days
total_days = len(pivot_df)

# Calculate the percentage
percentage = round((outperform_days / total_days) * 100)

print("Percentage of days when LARGE outperforms LARGEST:", percentage)

Percentage of days when LARGE outperforms LARGEST: 47

**Question 4: Trying Another Technical Indicators strategy**

What's the total gross profit (in THOUSANDS of $) you'll get from trading on CCI (no fees assumption)?

In [5]:
load_parquet_df = pd.read_parquet('/content/stocks_df_combined_trunc_2014_2023.parquet.brotli', engine='pyarrow')

In [7]:
load_parquet_df.head()

,Open,High,Low,Close,Adj Close_x,Volume,Ticker,Year,Month,Weekday,Date,growth_1d,growth_3d,growth_7d,growth_30d,growth_90d,growth_365d,growth_future_5d,SMA10,SMA20,growing_moving_average,high_minus_low_relative,volatility,is_positive_growth_5d_future,ticker_type,index_x,adx,adxr,apo,aroon_1,aroon_2,aroonosc,bop,cci,cmo,dx,macd,macdsignal,macdhist,macd_ext,macdsignal_ext,macdhist_ext,macd_fix,macdsignal_fix,macdhist_fix,mfi,minus_di,mom,plus_di,dm,ppo,roc,rocp,rocr,rocr100,rsi,slowk,slowd,fastk,fastd,fastk_rsi,fastd_rsi,trix,ultosc,willr,index_y,ad,adosc,obv,atr,natr,ht_dcperiod,ht_dcphase,ht_phasor_inphase,ht_phasor_quadrature,ht_sine_sine,ht_sine_leadsine,ht_trendmod,avgprice,medprice,typprice,wclprice,index,cdl2crows,cdl3blackrows,cdl3inside,cdl3linestrike,cdl3outside,cdl3starsinsouth,cdl3whitesoldiers,cdlabandonedbaby,cdladvancedblock,cdlbelthold,cdlbreakaway,cdlclosingmarubozu,cdlconcealbabyswall,cdlcounterattack,cdldarkcloudcover,cdldoji,cdldojistar,cdldragonflydoji,cdlengulfing,cdleveningdojistar,cdleveningstar,cdlgapsidesidewhite,cdlgravestonedoji,cdlhammer,cdlhangingman,cdlharami,cdlharamicross,cdlhighwave,cdlhikkake,cdlhikkakemod,cdlhomingpigeon,cdlidentical3crows,cdlinneck,cdlinvertedhammer,cdlkicking,cdlkickingbylength,cdlladderbottom,cdllongleggeddoji,cdllongline,cdlmarubozu,cdlmatchinglow,cdlmathold,cdlmorningdojistar,cdlmorningstar,cdlonneck,cdlpiercing,cdlrickshawman,cdlrisefall3methods,cdlseparatinglines,cdlshootingstar,cdlshortline,cdlspinningtop,cdlstalledpattern,cdlsticksandwich,cdltakuru,cdltasukigap,cdlthrusting,cdltristar,cdlunique3river,cdlupsidegap2crows,cdlxsidegap3methods,growth_dax_1d,growth_dax_3d,growth_dax_7d,growth_dax_30d,growth_dax_90d,growth_dax_365d,growth_snp500_1d,growth_snp500_3d,growth_snp500_7d,growth_snp500_30d,growth_snp500_90d,growth_snp500_365d,growth_dji_1d,growth_dji_3d,growth_dji_7d,growth_dji_30d,growth_dji_90d,growth_dji_365d,growth_epi_1d,growth_epi_3d,growth_epi_7d,growth_epi_30d,growth_epi_90d,growth_epi_365d,Quarter,gdppot_us_yoy,gdppot_us_qoq,cpi_core_yoy,cpi_core_mom,FEDFUNDS,DGS1,DGS5,DGS10,Adj Close_y,growth_gold_1d,growth_gold_3d,growth_gold_7d,growth_gold_30d,growth_gold_90d,growth_gold_365d,growth_wti_oil_1d,growth_wti_oil_3d,growth_wti_oil_7d,growth_wti_oil_30d,growth_wti_oil_90d,growth_wti_oil_365d,growth_brent_oil_1d,growth_brent_oil_3d,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
7011,37.349998,37.400002,37.099998,37.160000,31.233059,30632200.0,MSFT,2014,2014-01-01,3,2014-01-02,0.993317,0.996513,1.009782,1.006501,1.077462,1.266864,0.956136,36.992,37.3485,0,0.009605,9.176316,0,US,7011,18.602505,23.328791,-0.534679,35.714286,0.000000,-35.714286,-0.633322,57.700615,-0.028853,5.764086,0.008979,0.026960,-0.017981,-0.534679,-0.418105,-0.116574,0.007285,0.026036,-0.018751,38.060306,2.048754,0.639999,22.520941,1.825442,-1.426616,1.752463,0.017525,1.017525,101.752463,49.985573,61.280525,72.336814,36.111008,61.280525,0.00000,5.743953e+01,0.166871,55.208655,-22.748787,7011,7.556579e+09,7.773918e+06,1.123769e+10,0.578966,1.558037,18.305842,70.346530,0.371047,0.687761,0.941744,0.903735,0,37.252500,37.250000,37.220000,37.205000,7011,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-100,0,0,0,0,0,0,0,0,0,0,0.984075,0.990644,1.034663,1.027365,1.134529,1.390870,0.991138,0.994884,1.007512,1.022578,1.101280,1.330888,0.991837,0.997751,1.013575,1.029127,1.095323,1.270254,0.958716,0.968153,0.977206,1.000599,1.159267,0.989173,2014-01-01,0.018411,0.004604,0.01607,0.000857,0.07,0.13,1.72,3.00,14.23,1.019220,1.007318,1.016513,0.962899,0.877696,0.775267,0.969722,0.951356,0.960934,1.025906,0.896824,1.030002,0.972744,0.960777,0.964302,0.992998,0.970030,1.158676,NaN,NaN,NaN,NaN,NaN,NaN
7012,37.200001,37.220001,36.599998,36.910000,31.022930,31134800.0,MSFT,2014,2014-01-01,4,2014-01-03,0.993272,0.989809,1.007919,1.004627,1.089016,1.281318,0.976429,37.025,37.2470,0,0.019985,9.105631,0,US,7012,18.506853,22.757313,-0.504936,28.571429,0.000000,-28.571429,-0.467741,1.373763,-5.740186,17.263375,-0.013318,0.018904,-0.032223,-0.504936,-0.462970,-0.041966,-0.013726,0.018084,-0.031809,38.516104,2.402414,0.329998,20.806962,1.695053,-1.348265,0.902127,0.009021,1.009021,100.902127,47.129907,48.358266,61.507796,30.392278,48.358266,0.00000,3.055116e+01,0.160764,57.243893,-33.971246,7012,7.556579e+09,3.973096e+06,1.120655e+10,0.581898,1.576531,18.444363,86.443309,0.708958,0.323276,0.998074,0.749611,0,36.982500,36.910000,36.910000,36.910000,7012,0,0,0,0,0,0,0,0,0,-100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.003735,0.983916,1.027598,1.029062,1.123514,1.423095,0.999667,0.994731,1.001849,1.024331,1.105379,1.343967,1.001742,0.997922,1.010763,1.031500,1.101933,1.284453,1.009569,0.976287,0.981395,1.014423,1.190921,1.014622,2014-01-01,0.018411,0.004604,0.01607,0.000857,0.07,0.13,1.73,3.01,13.76,1.010939,1.029341,1.033378,0.972515,0.889017,0.782559,0.984493,0.946319,0.949954,1.006642,0.887085,1.027559,0.991742,0.961155,0.958139,0.984707,0.961500,1.143209,NaN,NaN,NaN,NaN,NaN,NaN
7013,36.849998,36.889999,36.110001,36.130001,30.367352,43603700.0,MSFT,2014,2014-01-01,0,2014-01-06,0.978868,0.965785,0.974380,0.974380,1.094529,1.290224,0.968170,37.013,37.1535,0,0.025685,9.620217,0,US,7013,19.092285,22.616849,-0.490513,21.428571,64.285714,42.857143,-0.923075,-96.631259,-20.920046,26.702902,-0.092858,-0.003448,-0.089410,-0.490513,-0.492229,0.001717,-0.088591,-0.003251,-0.085340,38.265836,2.720811,-0.119999,18.816978,1.573978,-1.311396,-0.331032,-0.003310,0.996690,99.668968,39.539977,22.621287,44.086693,1.360574,22.621287,0.00000,9.947598e-14,0.154013,46.949335,-71.291759,7013,7.515212e+09,-1.110538e+07,1.116295e+10,0.597476,1.653685,18.578180,90.773130,0.609358,-0.472000,0.999909,0.697501,0,36.495000,36.500000,36.376667,36.315001,7013,0,0,0,0,0,0,0,0,0,-100,0,-100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-100,-100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.999242,0.987002,1.009882,1.021958,1.120115,1.468689,0.997488,0.988319,0.996427,1.025486,1.120388,1.352642,0.997274,0.990857,1.004130,1.032972,1.111597,1.291133,0.994076,0.962156,0.972754,1.028817,1.254387,1.039418,2014-01-01,0.018411,0.004604,0.01607,0.000857,0.07,0.12,1.70,2.98,13.55,0.999516,1.029869,1.027135,0.984021,0.871322,0.784858,0.994359,0.949299,0.941645,1.001071,0.857077,1.060018,0.998503,0.963267,0.953798,0.998223,0.968951,1.168236,NaN,NaN,NaN,NaN,NaN,NaN
7014,36.330002,36.490002,36.209999,36.410000,30.602673,35802800.0,MSFT,2014,2014-01-01,1,2014-01-07,1.007749,0.979817,0.972489,0.973529,1.111027,1.306021,0.982698,36.974,37.0560,0,0.009150,9.927295,0,US,7014,19.635900,22.627050,-0.458910,14.285714,57.142857,42.857143,0.285705,-83.904297,-13.833138,26.702902,-0.131781,-0.029115,-0.102666,-0.458910,-0.511182,0.052272,-0.125457,-0.027692,-0.097764,37.956700,2.526467,-0.389999,17.983465,1.461551,-1.228410,-1.059781,-0.010598,0.989402,98.940219,43.083431,17.386982,29.455512,20.408094,17.386982,26.39322,8.797740e+00,0.146988,46.079184,-57.894689,7014,7.530556e+09,-1.138216e+07,1.119875e+10,0.580514,1.594380,18.684035,109.795353,0.340354,-0.604226,0.940908,0.425853,1,36.360001,36.350000,36.370000,36.380000,7014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,1.008294,1.011294,1.011279,1.034037,1.126975,1.487573,1.006082,1.003221,0.997752,1.023404,1.124113,1.373284,1.006444,1.005449,1.003098,1.032539,1.115109,1.310178,0.996424,1.000000,0.977206,1.038509,1.262119,1.035701,2014-01-01,0.018411,0.004604,0.01607,0.000857,0.07,0.13,1.69,2.96,12.92,0.993214,1.003592,1.012602,0.988661,0.866385,0.780076,1.002569,0.981454,0.940934,0.981454,0.850772,1.058418,1.005809,0.996010,0.958653,0.993430,0.977598,1.097648,NaN,NaN,NaN,NaN,NaN,NaN
7015,36.000000,36.139999,35.580002,35.759998,30.056356,59971700.0,MSFT,2014,2014-01-01,2,2014-01-08,0.982148,0.968843,0.958970,0.951823,1.073955,1.296943,1.027964,36.888,36.9085,0,0.018632,10.668724,1,US,7015,20.901876,23.479605,-0.408590,7.142857,50.000000,42.857143,-0.428576,-147.855135,-24.844967,37.359560,-0.212627,-0.065817,-0.146810,-0.408590,-0.515940,0.107350,-0.201782,-0.062510,-0.139271,36.902295,2.976003,-0.860001,16.201584,1.357154,-1.096388,-2.348445,-0.023484,0.976516,97.651555,37.577516,10.552862,16.853710,9.889919,10.552862,0.00000,8.797740e+00,0.139303,44.444691,-88.995238,7015,7.509137e+09,-1.727579e+07,1.113878e+10,0.598334,1.673194,18.648634,152.902839,0.201100,-0.798701,0.455501,-0.307404,1,35.870000,35.860001,35.826667,35.809999,7015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.999121,1.006644,1.000951,1.032142,1.152293,1.482527,0.999788,1.003342,0.997877,1.018135,1.121672,1.373424,0.995874,0.999560,0.999049,1.024773,1.109278,1.298728,1.003588,0.994076,0.971627,1.032615,1.246037,1.040053,2014-01-01,0.018411,0.004604,0.01607,0.000857,0.07,0.13,1.77,3.01,12.87,0.996665,0.989422,1.007565,0.984968,0.867223,0.762003,0.985694,0.982652,0.920355,0.973534,0.848621,1.037766,0.998137,1.002432,0.955161,0.973383,0.974977,1.100781,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
load_parquet_df.shape

(80762, 203)

In [46]:
# Calculate gross profit
def calculate_gross_profit(df):
    gross_profit = 0
    buy_operations = []  # Stores tuples of (buy_price, sell_price) for each buy operation
    for index, row in df.iterrows():
        if row['cci'] > 200 and row['Weekday'] == 4:  # Check for CCI > 200 and Friday
            buy_price = row['Adj Close_y']
            # Find the sell price after 5 trading days
            sell_index = index + 5
            if sell_index < len(df):  # Check if sell_index is within the bounds of the DataFrame
                sell_price = df.iloc[sell_index]['Adj Close_y']
                if not pd.isna(sell_price):  # Check if sell_price is not NaN
                    buy_operations.append((buy_price, sell_price))
    # Calculate gross profit from buy operations
    for buy_price, sell_price in buy_operations:
        profit = sell_price - buy_price
        if not pd.isna(profit):
          gross_profit += profit
          print("Profit for operation:", profit)
    return gross_profit

# Calculate gross profit over 10 years (260 weeks)
total_gross_profit = calculate_gross_profit(load_parquet_df)

# Convert total gross profit to thousands of dollars
total_gross_profit_thousands = round(total_gross_profit / 1000)

print("Total Gross Profit (in THOUSANDS of $):", total_gross_profit_thousands)

Profit for operation: 11.30000114440918
Profit for operation: 11.270000457763672
Profit for operation: 14.230000495910645
Profit for operation: -3.970001220703125
Profit for operation: -0.9800004959106445
Profit for operation: -7.920001029968262
Profit for operation: -0.029999732971191406
Profit for operation: 12.989999771118164
Profit for operation: 0.7899999618530273
Profit for operation: 12.480000495910645
Profit for operation: 6.710000038146973
Profit for operation: 0.48999977111816406
Profit for operation: -2.020000457763672
Profit for operation: -1.3800010681152344
Profit for operation: -2.1700000762939453
Profit for operation: -6.169999122619629
Profit for operation: 11.60999870300293
Profit for operation: -3.739999771118164
Profit for operation: 5.800000190734863
Profit for operation: -3.200000762939453
Profit for operation: 1.0600004196166992
Profit for operation: 11.119999885559082
Profit for operation: 3.7200002670288086
Profit for operation: 19.299999237060547
Profit for operation: 4.84999942779541
Profit for operation: 10.919999122619629
Profit for operation: -8.430000305175781
Profit for operation: -6.239999771118164
Profit for operation: -3.3200016021728516
Profit for operation: -6.909999847412109
Profit for operation: 0.9400005340576172
Profit for operation: -2.4200000762939453
Profit for operation: 0.039999961853027344
Profit for operation: -4.59999942779541
Profit for operation: -1.1000003814697266
Profit for operation: 0.4399995803833008
Profit for operation: 2.260000228881836
Profit for operation: -0.3900003433227539
Profit for operation: -1.5799999237060547
Profit for operation: 6.830000877380371
Profit for operation: 1.7100000381469727
Profit for operation: 5.100000381469727
Profit for operation: 2.1999998092651367
Profit for operation: 3.3199996948242188
Profit for operation: -2.390000343322754
Profit for operation: -0.9499998092651367
Profit for operation: 12.360000610351562
Profit for operation: 7.519998550415039
Profit for operation: 14.170000076293945
Profit for operation: -3.739999771118164
Profit for operation: 12.039999008178711
Profit for operation: 5.719999313354492
Profit for operation: 2.5699996948242188
Profit for operation: 12.449999809265137
Profit for operation: 13.219999313354492
Profit for operation: 10.639999389648438
Profit for operation: 3.570000648498535
Profit for operation: 2.770000457763672
Profit for operation: 6.689999580383301
Profit for operation: 2.0900001525878906
Profit for operation: 15.389999389648438
Profit for operation: 2.8299999237060547
Profit for operation: -2.669999122619629
Profit for operation: -12.34000015258789
Profit for operation: -7.149999618530273
Profit for operation: -3.320000648498535
Profit for operation: 2.75
Profit for operation: 22.360000610351562
Profit for operation: 12.579999923706055
Profit for operation: 3.810000419616699
Profit for operation: -2.3400001525878906
Profit for operation: 7.000000953674316
Profit for operation: 11.930000305175781
Profit for operation: 16.66999912261963
Profit for operation: 4.369999885559082
Profit for operation: 9.869999885559082
Profit for operation: 1.7700004577636719
Profit for operation: 0.09000015258789062
Profit for operation: 2.8299999237060547
Profit for operation: 1.8299999237060547
Profit for operation: 2.1700000762939453
Profit for operation: 3.1399993896484375
Profit for operation: 0.8900003433227539
Profit for operation: -1.0500001907348633
Profit for operation: -4.340000152587891
Profit for operation: -6.180000305175781
Profit for operation: -12.820000648498535
Profit for operation: -4.630000114440918
Profit for operation: 33.959999084472656
Profit for operation: 36.44000053405762
Profit for operation: 10.000000953674316
Profit for operation: -1.5599994659423828
Profit for operation: -0.8200006484985352
Profit for operation: -0.5
Profit for operation: -10.05000114440918
Profit for operation: -0.5500001907348633
Profit for operation: 11.64000129699707
Profit for operation: -0.9299983978271484
Profit for operation: 4.010000228881836
Profit for operation: 6.529998779296875
Profit for operation: -2.689999580383301
Profit for operation: 3.660000801086426
Profit for operation: -3.6100006103515625
Profit for operation: -1.0299997329711914
Profit for operation: -1.359999656677246
Profit for operation: 4.640000343322754
Profit for operation: 0.7100000381469727
Profit for operation: -3.2699995040893555
Profit for operation: 2.4200010299682617
Profit for operation: -3.1299991607666016
Profit for operation: 1.9399986267089844
Profit for operation: 7.489999771118164
Profit for operation: -0.880000114440918
Profit for operation: -3.1000003814697266
Profit for operation: -11.890000343322754
Profit for operation: 2.4499998092651367
Profit for operation: -2.989999771118164
Profit for operation: 13.710000038146973
Profit for operation: 17.400001525878906
Profit for operation: -0.1100006103515625
Profit for operation: 10.6899995803833
Profit for operation: 3.1599998474121094
Profit for operation: 1.8899993896484375
Profit for operation: -13.430000305175781
Profit for operation: 0.0
Profit for operation: 13.869999885559082
Profit for operation: 4.649999618530273
Profit for operation: 3.6399993896484375
Profit for operation: 8.659998893737793
Profit for operation: -2.2699995040893555
Profit for operation: 4.530000686645508
Profit for operation: -1.510000228881836
Profit for operation: 42.620001792907715
Profit for operation: 12.75999927520752
Profit for operation: 7.479999542236328
Profit for operation: 5.789999008178711
Profit for operation: 12.910000801086426
Profit for operation: 10.169999122619629
Profit for operation: 4.430000305175781
Profit for operation: 5.350000381469727
Profit for operation: 5.65000057220459
Profit for operation: 5.0099992752075195
Profit for operation: 1.7799997329711914
Profit for operation: -2.9900007247924805
Profit for operation: -6.749999046325684
Profit for operation: -2.7400007247924805
Profit for operation: -8.370000839233398
Profit for operation: -10.709999084472656
Profit for operation: -8.559999465942383
Profit for operation: -7.450000762939453
Profit for operation: -0.36999988555908203
Profit for operation: 8.000000953674316
Profit for operation: 13.14000129699707
Profit for operation: 16.380001068115234
Profit for operation: 14.430000305175781
Profit for operation: 9.529999732971191
Profit for operation: 5.710000038146973
Profit for operation: 10.529999732971191
Profit for operation: -1.1399993896484375
Profit for operation: -1.1899995803833008
Profit for operation: 2.220001220703125
Profit for operation: 1.5900001525878906
Profit for operation: -0.3400001525878906
Profit for operation: 1.2000007629394531
Profit for operation: 11.460000038146973
Profit for operation: 0.5900001525878906
Profit for operation: -0.4099998474121094
Profit for operation: 17.230000495910645
Profit for operation: 8.720000267028809
Profit for operation: 11.729999542236328
Profit for operation: 3.2500009536743164
Profit for operation: -13.859999656677246
Profit for operation: 0.8600006103515625
Profit for operation: -5.409999847412109
Profit for operation: 0.3299999237060547
Profit for operation: -2.830000877380371
Profit for operation: -1.2100000381469727
Profit for operation: -4.270000457763672
Profit for operation: 4.599998474121094
Profit for operation: 48.08000183105469
Profit for operation: 12.649999618530273
Profit for operation: 14.979999542236328
Profit for operation: 29.009998321533203
Profit for operation: 8.130000114440918
Profit for operation: -19.420001983642578
Profit for operation: -8.649999618530273
Profit for operation: -11.09000015258789
Profit for operation: -1.1900005340576172
Profit for operation: -7.950000762939453
Profit for operation: -11.819999694824219
Profit for operation: 5.729999542236328
Profit for operation: 5.430000305175781
Profit for operation: -6.2699995040893555
Profit for operation: -4.620000839233398
Profit for operation: 11.559999465942383
Profit for operation: 61.4500036239624
Profit for operation: 12.060001373291016
Profit for operation: 5.790000915527344
Profit for operation: 14.220000267028809
Profit for operation: 22.469999313354492
Profit for operation: 9.829998970031738
Profit for operation: 15.620000839233398
Profit for operation: 7.909999847412109
Profit for operation: -2.440000534057617
Profit for operation: 2.8000001907348633
Profit for operation: -2.1199989318847656
Profit for operation: -0.31999969482421875
Profit for operation: -14.829999923706055
Profit for operation: -2.679999351501465
Profit for operation: -10.359999656677246
Profit for operation: -11.800000190734863
Profit for operation: -6.590000152587891
Profit for operation: -5.909999847412109
Profit for operation: -1.6899995803833008
Profit for operation: 5.559999465942383
Profit for operation: 3.030000686645508
Profit for operation: -7.539999961853027
Profit for operation: -2.7200002670288086
Profit for operation: 5.470001220703125
Profit for operation: -0.8000001907348633
Profit for operation: 2.0699996948242188
Profit for operation: -2.5799999237060547
Profit for operation: 10.520000457763672
Profit for operation: -4.340000152587891
Profit for operation: 6.720001220703125
Profit for operation: 12.0
Profit for operation: -4.620000839233398
Profit for operation: 0.8399991989135742
Profit for operation: -2.4600000381469727
Profit for operation: 10.869998931884766
Profit for operation: 10.820000648498535
Profit for operation: 3.9099998474121094
Profit for operation: 5.790000915527344
Profit for operation: 6.659999847412109
Profit for operation: 2.8000001907348633
Profit for operation: -0.31999969482421875
Profit for operation: 1.239999771118164
Profit for operation: -9.219999313354492
Profit for operation: -2.7100000381469727
Profit for operation: -10.359999656677246
Profit for operation: -11.800000190734863
Profit for operation: -11.339999198913574
Profit for operation: -0.39999961853027344
Profit for operation: 7.729999542236328
Profit for operation: 61.4500036239624
Profit for operation: 10.09000015258789
Profit for operation: 18.0
Profit for operation: 16.21000099182129
Profit for operation: 11.950000762939453
Profit for operation: 0.6000003814697266
Profit for operation: -0.7700004577636719
Profit for operation: -13.720000267028809
Profit for operation: 10.389999389648438
Profit for operation: -2.2100000381469727
Profit for operation: -11.800000190734863
Profit for operation: -6.590000152587891
Profit for operation: -3.7100000381469727
Profit for operation: 7.220001220703125
Profit for operation: 3.8299999237060547
Profit for operation: 8.470000267028809
Profit for operation: -1.989999771118164
Profit for operation: 12.149999618530273
Profit for operation: 5.859999656677246
Profit for operation: -1.8299999237060547
Profit for operation: 1.1399993896484375
Profit for operation: 3.0799999237060547
Profit for operation: 1.3299999237060547
Profit for operation: -1.6999998092651367
Profit for operation: 2.9499998092651367
Profit for operation: 27.99000072479248
Profit for operation: 34.030001640319824
Profit for operation: 18.649999618530273
Profit for operation: 27.6299991607666
Profit for operation: 9.249999046325684
Profit for operation: 8.230000495910645
Profit for operation: 4.470000267028809
Profit for operation: 2.8700008392333984
Profit for operation: -6.040000915527344
Profit for operation: -3.4300003051757812
Profit for operation: -1.409998893737793
Profit for operation: -11.729999542236328
Profit for operation: 7.470000267028809
Profit for operation: -1.1399993896484375
Profit for operation: 47.84000110626221
Profit for operation: 14.329999923706055
Profit for operation: 11.969999313354492
Profit for operation: 4.679999351501465
Profit for operation: 4.829998970031738
Profit for operation: 3.890000343322754
Profit for operation: -4.379999160766602
Profit for operation: -7.260000228881836
Profit for operation: 2.239999771118164
Profit for operation: 4.770000457763672
Profit for operation: 7.530000686645508
Profit for operation: -0.10000038146972656
Profit for operation: 0.48999977111816406
Profit for operation: -0.9200000762939453
Profit for operation: 14.050000190734863
Profit for operation: 12.440000534057617
Profit for operation: -0.9300003051757812
Profit for operation: 3.5600013732910156
Profit for operation: -10.519999504089355
Profit for operation: -8.179999351501465
Profit for operation: -6.430000305175781
Profit for operation: 0.5500001907348633
Profit for operation: 43.51000118255615
Profit for operation: 21.09999942779541
Profit for operation: 22.42000102996826
Profit for operation: 17.5
Profit for operation: -3.309999465942383
Profit for operation: 6.560001373291016
Profit for operation: -4.649999618530273
Profit for operation: -9.690000534057617
Profit for operation: -4.0
Profit for operation: 8.979999542236328
Profit for operation: -3.359999656677246
Profit for operation: 17.660000801086426
Profit for operation: 7.619999885559082
Profit for operation: 3.0699996948242188
Profit for operation: 1.890000343322754
Profit for operation: 8.139999389648438
Profit for operation: 3.189999580383301
Profit for operation: 8.269999504089355
Profit for operation: -5.829998970031738
Profit for operation: 1.369999885559082
Profit for operation: -18.26999855041504
Profit for operation: -14.199999809265137
Profit for operation: -14.670001029968262
Profit for operation: -0.8299999237060547
Profit for operation: 1.019998550415039
Profit for operation: 1.7799997329711914
Profit for operation: 14.910000801086426
Profit for operation: -4.380000114440918
Profit for operation: 3.4200000762939453
Profit for operation: -9.600000381469727
Profit for operation: -1.25
Profit for operation: 5.5099992752075195
Profit for operation: 6.050000190734863
Profit for operation: -1.8399991989135742
Profit for operation: 0.10000038146972656
Profit for operation: -9.880001068115234
Profit for operation: 1.5300006866455078
Profit for operation: 41.30000019073486
Profit for operation: 20.69999885559082
Profit for operation: 3.439999580383301
Profit for operation: 19.810001373291016
Profit for operation: -7.829999923706055
Profit for operation: -0.7299995422363281
Profit for operation: -12.409998893737793
Profit for operation: -0.37999916076660156
Profit for operation: 5.969999313354492
Profit for operation: 11.819999694824219
Profit for operation: 9.100000381469727
Profit for operation: -0.5
Profit for operation: 0.21000003814697266
Profit for operation: 5.2400007247924805
Profit for operation: 2.8400001525878906
Profit for operation: 47.900001525878906
Profit for operation: 26.999999046325684
Profit for operation: 14.65999984741211
Profit for operation: 4.590000152587891
Profit for operation: 8.939998626708984
Profit for operation: 8.65999984741211
Profit for operation: -6.159999847412109
Profit for operation: 1.2500009536743164
Profit for operation: -5.90000057220459
Profit for operation: 1.4100008010864258
Profit for operation: -3.929999351501465
Profit for operation: 6.539999008178711
Profit for operation: 0.26000022888183594
Profit for operation: 10.889999389648438
Profit for operation: 8.129999160766602
Profit for operation: 17.160000801086426
Profit for operation: -1.75
Profit for operation: -10.399998664855957
Profit for operation: -1.6200008392333984
Profit for operation: 14.760001182556152
Profit for operation: 10.380001068115234
Profit for operation: 13.899999618530273
Profit for operation: 16.989998817443848
Profit for operation: 2.4499998092651367
Profit for operation: -1.989999771118164
Profit for operation: 7.100000381469727
Profit for operation: 0.3900003433227539
Profit for operation: -9.739998817443848
Profit for operation: 4.789999008178711
Profit for operation: -6.410000801086426
Profit for operation: -4.739999771118164
Profit for operation: -12.699999809265137
Profit for operation: 4.309999465942383
Profit for operation: 4.119998931884766
Profit for operation: -1.9400005340576172
Profit for operation: 0.9099998474121094
Profit for operation: 4.220000267028809
Profit for operation: -0.14999961853027344
Profit for operation: -4.819999694824219
Profit for operation: 10.729999542236328
Profit for operation: 22.589998245239258
Profit for operation: 7.380000114440918
Profit for operation: -2.90000057220459
Profit for operation: -3.219999313354492
Profit for operation: -0.26000022888183594
Profit for operation: 0.1099996566772461
Profit for operation: -1.8099994659423828
Profit for operation: -4.109999656677246
Profit for operation: -12.080000877380371
Profit for operation: -0.4099998474121094
Profit for operation: 5.340001106262207
Profit for operation: 7.5099992752075195
Profit for operation: 1.890000343322754
Profit for operation: -1.6200008392333984
Profit for operation: -1.4300003051757812
Profit for operation: 1.8400001525878906
Profit for operation: 1.9700002670288086
Profit for operation: -1.7100000381469727
Profit for operation: 0.09000015258789062
Profit for operation: 3.2799997329711914
Profit for operation: -6.7400007247924805
Profit for operation: -2.239999771118164
Profit for operation: -7.590001106262207
Profit for operation: -6.290000915527344
Profit for operation: -4.84999942779541
Profit for operation: -1.2700004577636719
Profit for operation: 2.729999542236328
Profit for operation: 14.579999923706055
Profit for operation: 0.4499988555908203
Profit for operation: 3.4800004959106445
Profit for operation: 6.129999160766602
Profit for operation: 6.749999046325684
Profit for operation: 17.410000801086426
Profit for operation: 7.25
Profit for operation: 18.010000228881836
Profit for operation: -7.369999885559082
Profit for operation: -5.739999771118164
Profit for operation: -5.469999313354492
Profit for operation: -15.000000953674316
Profit for operation: -7.770000457763672
Profit for operation: 1.1000003814697266
Profit for operation: -1.960000991821289
Profit for operation: 0.4500007629394531
Profit for operation: -3.549999237060547
Profit for operation: -1.5400009155273438
Profit for operation: 6.099998474121094
Profit for operation: 10.329998970031738
Profit for operation: 0.2199993133544922
Profit for operation: -4.189999580383301
Profit for operation: -2.809999465942383
Profit for operation: 6.1399993896484375
Profit for operation: 6.7699995040893555
Profit for operation: 9.200000762939453
Profit for operation: 7.35999870300293
Profit for operation: 6.439999580383301
Profit for operation: -2.9300003051757812
Profit for operation: -10.489999771118164
Profit for operation: -6.300000190734863
Profit for operation: 3.6100006103515625
Profit for operation: 0.7899999618530273
Profit for operation: 9.729999542236328
Profit for operation: 2.4300003051757812
Total Gross Profit (in THOUSANDS of $): 2

So, following this approach for 10 years, Total Gross Profit (in THOUSANDS of $): 2

**[EXPLORATORY] Question 5: Finding Your Strategy for IPOs**

You've seen in the first questions that the median and average investments are negative in IPOs, and you can't blindly invest in all deals.

How would you correct/refine the approach? Briefly describe the steps and the data you'll try to get (it should be generally feasible to do it from public sources - no access to internal data of companies)?

E.g. (some ideas) Do you want to focus on the specific vertical? Do you want to build a smart comparison vs. existing stocks on the market? Or you just will want to get some features (which features?) like total number of people in a company to find a segment of "successful" IPOs?

Yes, blindly investing in IPOs is a bad idea and can lead to bad losses.
In general, my approach would be to research about the company's motive behind raising capital and if it is for expansion(estimate the potential benefits) then it can be considered. Also, data about company's prospectus through Form S-1, company's value, profits, EBITDA, growth, how old the company is would be looked.

As investing in IPOs is highly risky, perhaps, deciding about exit strategy and period of holding has to be planned carefully and adapted according to the fluctation of prices.